import pandas as pd

# This file contains the data for business outcomes and maturity descriptions

# Define option descriptions
OPTION_DESCRIPTIONS = {
    "Basic": {
        "value": 0,
        "description": "Minimal functionality, often manual processes, requiring significant user effort and offering limited capabilities."
    },
    "Advanced": {
        "value": 0.33,
        "description": "Standard industry functionality with some automation and integration, providing reliable but not exceptional service."
    },
    "Leading": {
        "value": 0.66,
        "description": "Above average capabilities with significant automation, integration, and optimization, offering competitive advantage."
    },
    "Emerging": {
        "value": 1.0,
        "description": "Cutting-edge, innovative capabilities leveraging AI, machine learning, and advanced technologies to deliver exceptional service."
    }
}

# Convert process details into dataframe
def load_process_details():
    data = [
        # Stage 1: Payment Initiation & Data Capture
        {
            "qid": "1A", "stage": "Payment Initiation & Data Capture", 
            "process": "Channel Access & Log-In",
            "description": "Provides the customer or corporate user with secure entry points to initiate payments—mobile app, web portal, POS, wallet or ERP/TMS integration, bulk-file upload or APIs/host-to-host.",
            "basic": "• Multiple siloed channels with separate credentials (e.g. branch login, web login, mobile login).\n• No single-sign-on; users must reauthenticate per channel.\n• Slow password/PIN flows, little automation in session management.",
            "advanced": "• Centralized IAM with single-sign-on across channels.\n• Persistent sessions via secure cookies or device trust.\n• Basic adaptive MFA (e.g. step-up for high-value payments).",
            "leading": "• Fully unified CIAM platform: SSO, OAuth2/OIDC, device fingerprinting.\n• Contextual authentication (risk-based MFA triggered automatically).\n• API-first design so third-party apps (ERP, fintech partners) share the same login flow.",
            "emerging": "• Passwordless with behavioral biometrics.\n• AI-driven fraud prevention in login (behavioral biometrics, continuous authentication).\n• Decentralized identity (DID) using verifiable credentials for corporate users.",
        },
        {
            "qid": "1B", "stage": "Payment Initiation & Data Capture", 
            "process": "Payment Setup",
            "description": "The screen or API call where payer enters or uploads the payment details: retail single-payment UI or corporate bulk file (e.g. payroll).",
            "basic": "• Manual UI form for single payment with limited reuse of payees.\n• Corporate uses flat-file templates via SFTP.\n• No intelligent defaults; all fields must be typed.",
            "advanced": "• Pre-populated beneficiary lists, autocomplete of recurring payees.\n• Corporate B2B portal supports CSV/ISO 20022 XML upload with template validation.\n• \"Save as draft\" workflows for approval queues.",
            "leading": "• Guided UI with next-best-action suggestions (AI-driven) for payees/amounts.\n• Bulk template import via API, with dynamic loading of corporate ACH/RTGS parameters.\n• Auto-grouping of bulk payments by payee or category for faster entry.",
            "emerging": "• Conversational-UI or voice-driven payment setup.\n• Zero-touch invoice-to-pay: AI ingests PDF invoices, auto-creates payment batches.\n• Real-time integrations with ERP to auto-trigger payments on invoice receipt.",
        },
        {
            "qid": "1C", "stage": "Payment Initiation & Data Capture", 
            "process": "Data Entry & Input Validation",
            "description": "Ensures the data entered is syntactically & semantically correct—format checks (IBAN, BIC), mandatory fields, and optional real-time lookups (account status, card BIN).",
            "basic": "• Basic form validation with generic error messages.\n• Manual correction loops with full page refresh.\n• No contextual help or inline validation.",
            "advanced": "• Inline validation with field-specific error messages.\n• Format detection & normalization (e.g. auto-format card numbers).\n• Address verification against postal database.",
            "leading": "• Dynamic validation based on payment type & destination country.\n• Beneficiary name & account validation in real-time.\n• PAN/CVV validation against card BIN database.",
            "emerging": "• AI-powered predictive field completion & error correction.\n• Real-time IBAN lookup with beneficiary confirmation API.\n• ML anomaly detection to flag unusual payment characteristics.",
        },
        {
            "qid": "1D", "stage": "Payment Initiation & Data Capture", 
            "process": "Submission & Order Creation",
            "description": "Captures the completed payment order, creates the payment record, and hands off to downstream processing—confirms submission & provides reference number.",
            "basic": "• Batch processing with end-of-day execution.\n• No real-time feedback or status tracking.\n• Manual record creation & tracking.",
            "advanced": "• Real-time order creation with immediate confirmation.\n• Digital receipt with unique reference number.\n• Payment status tracking in customer portal.",
            "leading": "• Event streaming architecture with guaranteed order capture.\n• Multi-channel payment status notifications.\n• Payment history searchable by multiple parameters (date, amount, payee).",
            "emerging": "• Zero-latency distributed ledger recording.\n• Blockchain-based immutable payment record.\n• Full payment lifecycle visibility with real-time status changes.",
        },
        
        # Stage 2: Authentication & Identity Validation
        {
            "qid": "2A", "stage": "Authentication & Identity Validation", 
            "process": "Primary Authentication",
            "description": "Confirms the identity of the payment initiator through username/password challenge, biometrics, passkeys, or other credentials.",
            "basic": "• Simple username/password authentication.\n• No biometric options, only PIN/password.\n• Long session timeout requiring frequent re-auth.",
            "advanced": "• Industry-standard 2FA (SMS OTP, email links).\n• Basic biometric options (fingerprint, face).\n• Security questions for high-risk actions.",
            "leading": "• FIDO2/WebAuthn support with token-based auth.\n• Multiple biometric options on all channels.\n• Intelligent session management based on risk.",
            "emerging": "• Passwordless with passkeys for all channels.\n• Behavioral biometrics as primary auth factor.\n• Continuous authentication throughout payment journey.",
        },
        {
            "qid": "2B", "stage": "Authentication & Identity Validation", 
            "process": "Multi-Factor Authentication",
            "description": "Adds additional verification factors when required by transaction risk, compliance requirements, or to ensure non-repudiation.",
            "basic": "• SMS one-time codes as only second factor.\n• No risk-based MFA triggers.\n• Blanket approach requiring same MFA for all payments.",
            "advanced": "• App-based authenticator options.\n• Basic risk rules trigger step-up auth.\n• Configurable MFA thresholds based on amount.",
            "leading": "• Multiple authenticator options (TOTP, push notifications).\n• Out-of-band verification through multiple channels.\n• Context-aware adaptive authentication.",
            "emerging": "• Presence-based silent authentication.\n• Biometric MFA with liveness detection.\n• AI-driven continuous risk assessment.",
        },
        {
            "qid": "2C", "stage": "Authentication & Identity Validation", 
            "process": "Corporate Authorization",
            "description": "For business accounts, validates the initiator has proper entitlements, mandate & signing authority, and enforces payment limits by role & amount.",
            "basic": "• Static role-based access control.\n• Manual entitlement verification.\n• No integration with corporate hierarchy data.",
            "advanced": "• Automated limit checks during initiation.\n• Pre-defined approval workflows.\n• Role-based dashboards & controls.",
            "leading": "• Dynamic mandate checking against corporate structure.\n• Real-time signature verification against mandate database.\n• Complex approval matrix support (multiple approvers by criteria).",
            "emerging": "• Decentralized identity verification with VC/blockchain.\n• Algorithm-based smart approval routing.\n• Integration with corporate governance systems.",
        },
        {
            "qid": "2D", "stage": "Authentication & Identity Validation", 
            "process": "Session Security",
            "description": "Prevents session hijacking, maintains secure payment context, and protects the authenticated state from theft or replay attacks.",
            "basic": "• Basic cookie-based sessions.\n• Short timeouts with full re-auth required.\n• No detection of session anomalies.",
            "advanced": "• Encrypted session tokens with regular rotation.\n• Session binding to IP address.\n• Automatic logout on inactivity.",
            "leading": "• Advanced device fingerprinting.\n• Certificate pinning for mobile apps.\n• Session continuity across channels.",
            "emerging": "• Zero trust architecture with continuous validation.\n• Real-time risk scoring of session behaviors.\n• Quantum-resistant session cryptography.",
        },
        
        # Stage 3: Pre-Submission Validation
        {
            "qid": "3A", "stage": "Pre-Submission Validation", 
            "process": "Format & Completeness Checks",
            "description": "Validates all required fields are present, properly formatted, and meet the criteria for the specific payment type, channel, and destination.",
            "basic": "• Basic required field validation.\n• Generic error messages.\n• Limited format validation (length, character type).",
            "advanced": "• Payment-type specific validation rules.\n• Clear error identification with correction guidance.\n• Format standardization before submission.",
            "leading": "• Dynamic field requirements based on payment context.\n• Real-time field-level validation for all inputs.\n• Format transformation & normalization.",
            "emerging": "• AI-based predictive validation of complex fields.\n• Metadata enrichment from multiple sources.\n• Semantic validation of payment purpose.",
        },
        {
            "qid": "3B", "stage": "Pre-Submission Validation", 
            "process": "Business Rule Enforcement",
            "description": "Checks payment against business policies like daily limits, duplicate detection, allowed destinations, frequency caps, and balance requirements.",
            "basic": "• Static hard-coded business rules.\n• Basic duplicate payment detection.\n• Manual balance checks.",
            "advanced": "• Centralized rules engine with versioning.\n• Automated funds availability verification.\n• Real-time limit monitoring.",
            "leading": "• Dynamic rules triggered by contextual factors.\n• ML-based duplicate detection (fuzzy matching).\n• Cross-channel rule consistency.",
            "emerging": "• Self-optimizing rules based on payment patterns.\n• Predictive cash flow verification.\n• Natural language policy definition.",
        },
        {
            "qid": "3C", "stage": "Pre-Submission Validation", 
            "process": "Preliminary Compliance Screening",
            "description": "Performs initial screening of payment against sanctions lists, high-risk countries, and suspicious patterns before committing to the payment flow.",
            "basic": "• Basic screening against outdated sanctions lists.\n• No real-time screening during payment initiation.\n• Binary pass/fail with manual review process.",
            "advanced": "• Daily-updated screening lists.\n• Real-time initial screening during payment entry.\n• Name matching with fuzzy logic.",
            "leading": "• API-connected sanctions screening service.\n• Risk-based screening depth based on payment profile.\n• Automated resolution of common false positives.",
            "emerging": "• Pre-emptive AI screening with behavioral context.\n• Real-time regulatory updates integration.\n• Cross-border compliance determination with country-specific rules.",
        },
        {
            "qid": "3D", "stage": "Pre-Submission Validation", 
            "process": "User Experience & Error Handling",
            "description": "Provides clear feedback on validation issues, guides correction steps, and maintains data persistence during error resolution.",
            "basic": "• Generic error messages without correction guidance.\n• No in-line validation support.\n• Page reload required for each correction.",
            "advanced": "• Field-specific error messaging.\n• Suggestions for common errors.\n• Form state persistence during validation.",
            "leading": "• Contextual help with correction procedures.\n• Visual indicators of field validation status.\n• One-click fixes for common errors.",
            "emerging": "• AI-powered error correction suggestions.\n• Natural language explanation of validation errors.\n• Predictive input assistance to prevent errors.",
        },
        
        # Stage 4: Payment Orchestration & Routing
        {
            "qid": "4A", "stage": "Payment Orchestration & Routing", 
            "process": "Payment Network Selection",
            "description": "Determines the optimal payment rail or network based on cost, speed, destination, amount, and other factors.",
            "basic": "• Manual network selection by operator.\n• Limited network connectivity options.\n• Static routing based on hard-coded rules.",
            "advanced": "• Automated routing based on predefined rules.\n• Support for major domestic and international networks.\n• Alternative routing for network outages.",
            "leading": "• Dynamic routing optimization based on multiple factors.\n• Real-time network status monitoring.\n• Cost-optimized routing with fee transparency.",
            "emerging": "• AI-driven intelligent routing with predictive optimization.\n• Real-time network performance benchmarking.\n• Self-learning routing algorithms that adapt to changing conditions.",
        },
        {
            "qid": "4B", "stage": "Payment Orchestration & Routing", 
            "process": "Processing Schedule Management",
            "description": "Handles timing dependencies, cutoff windows, value dating, and ensures payments are submitted within appropriate processing windows.",
            "basic": "• Manual scheduling and cutoff monitoring.\n• Fixed processing windows for all payments.\n• Limited visibility into processing timeframes.",
            "advanced": "• Automated cutoff management by payment type.\n• Pre-scheduled payment queuing.\n• Warning alerts for approaching cutoffs.",
            "leading": "• Dynamic processing window optimization.\n• Real-time status visibility across all networks.\n• Predictive cutoff management with queue prioritization.",
            "emerging": "• Autonomous schedule optimization with machine learning.\n• Predictive cutoff risk assessment.\n• Self-adjusting queuing based on network conditions.",
        },
        {
            "qid": "4C", "stage": "Payment Orchestration & Routing", 
            "process": "Fee Calculation & Application",
            "description": "Determines, discloses, and applies the appropriate fees for the payment based on network, amount, customer tier, and other criteria.",
            "basic": "• Static fee schedules for all customers.\n• Manual fee calculation and application.\n• Limited fee transparency or estimation.",
            "advanced": "• Customer tier-based fee structures.\n• Automated fee calculation and application.\n• Basic fee disclosure before payment submission.",
            "leading": "• Dynamic fee optimization based on multiple factors.\n• Real-time fee calculation with full transparency.\n• Fee comparison across available payment routes.",
            "emerging": "• AI-driven fee optimization with customer behavior analysis.\n• Predictive fee modeling based on historical patterns.\n• Dynamic pricing strategies with machine learning.",
        },
        {
            "qid": "4D", "stage": "Payment Orchestration & Routing", 
            "process": "Notification & Communication",
            "description": "Informs parties about payment status, routing decisions, and ensures transparency throughout the orchestration process.",
            "basic": "• Basic email confirmations only.\n• No real-time status updates.\n• Limited visibility into payment progress.",
            "advanced": "• Multi-channel notifications (email, SMS, app).\n• Status tracking through customer portal.\n• Automated alerts for key payment events.",
            "leading": "• Real-time push notifications across channels.\n• Interactive payment tracking with milestone visibility.\n• Personalized notification preferences by customer.",
            "emerging": "• Predictive status updates before events occur.\n• Conversational AI notifications with interactive resolution.\n• Context-aware notification timing and channel selection.",
        },
        
        # Stage 5: Risk, Fraud & Compliance
        {
            "qid": "5A", "stage": "Risk, Fraud & Compliance", 
            "process": "Fraud Detection & Prevention",
            "description": "Monitors and screens payments for suspicious patterns or anomalies that might indicate fraudulent activity.",
            "basic": "• Rule-based fraud detection with limited rules.\n• High false positive rates.\n• Manual review of flagged transactions.",
            "advanced": "• Expanded rule set with transaction profiling.\n• Risk scoring based on multiple factors.\n• Semi-automated case management.",
            "leading": "• Machine learning models for fraud detection.\n• Behavioral biometrics integration.\n• Network analysis to detect coordinated fraud.",
            "emerging": "• AI-powered real-time fraud prevention.\n• Predictive fraud analytics with minimal false positives.\n• Self-learning models that adapt to new fraud patterns.",
        },
        {
            "qid": "5B", "stage": "Risk, Fraud & Compliance", 
            "process": "Sanctions & Watchlist Screening",
            "description": "Screens payment parties against relevant sanctions lists, PEP lists, and other regulatory watchlists.",
            "basic": "• Basic name matching against limited lists.\n• High false positive rates.\n• Manual resolution of all screening hits.",
            "advanced": "• Fuzzy matching algorithms.\n• Regular watchlist updates.\n• Automated clearing of obvious false positives.",
            "leading": "• Advanced name matching with cultural variants.\n• Risk-based screening approach.\n• Machine learning for false positive reduction.",
            "emerging": "• AI-driven entity resolution with contextual analysis.\n• Real-time global regulatory intelligence integration.\n• Predictive compliance with minimal human intervention.",
        },
        {
            "qid": "5C", "stage": "Risk, Fraud & Compliance", 
            "process": "Anti-Money Laundering Controls",
            "description": "Applies AML monitoring, suspicious activity detection, and regulatory compliance checks to payment flows.",
            "basic": "• Simple threshold-based AML monitoring.\n• Manual SAR/STR filing process.\n• Limited transaction pattern analysis.",
            "advanced": "• Risk-based customer segmentation.\n• Automated alert generation based on scenarios.\n• Case management workflow for investigations.",
            "leading": "• Behavioral analytics for anomaly detection.\n• Network analysis to identify money laundering rings.\n• Machine learning-enhanced alert prioritization.",
            "emerging": "• AI-driven contextual analysis of transaction intent.\n• Predictive risk modeling across customer relationships.\n• Autonomous AML with minimal false positives.",
        },
        {
            "qid": "5D", "stage": "Risk, Fraud & Compliance", 
            "process": "Case Management & Decision Flow",
            "description": "Manages the workflow for investigating flagged transactions, collecting additional information, and determining resolution.",
            "basic": "• Manual case tracking and assignment.\n• Email-based communication for investigations.\n• Limited audit trail of decisions.",
            "advanced": "• Structured case management system.\n• Semi-automated case assignment.\n• Standardized investigation procedures.",
            "leading": "• Dynamic case prioritization and routing.\n• Machine learning-assisted investigation guidance.\n• Complete audit trail with decision support.",
            "emerging": "• AI-driven case resolution recommendations.\n• Predictive case triage and resource allocation.\n• Self-optimizing investigation workflows.",
        },
        
        # Stage 6: Final Authorisation & Approval
        {
            "qid": "6A", "stage": "Final Authorisation & Approval", 
            "process": "Payment Authorization",
            "description": "Final approval of the payment based on all previously completed validations, balances, and risk assessments.",
            "basic": "• Manual authorization by operations staff.\n• Binary approve/reject decisions.\n• Limited straight-through processing.",
            "advanced": "• Automated authorization based on predefined rules.\n• Risk-based authorization levels.\n• Straight-through processing for low-risk payments.",
            "leading": "• Dynamic authorization with contextual decision logic.\n• Real-time balance verification and holds.\n• Automated exception handling for common issues.",
            "emerging": "• AI-driven adaptive authorization with behavioral analysis.\n• Predictive authorization based on historical patterns.\n• Self-optimizing decision frameworks with minimal exceptions.",
        },
        {
            "qid": "6B", "stage": "Final Authorisation & Approval", 
            "process": "Multiple Approver Orchestration",
            "description": "Manages complex approval workflows involving multiple parties, approval thresholds, and delegated authorities.",
            "basic": "• Fixed, linear approval chains.\n• Manual tracking of approval status.\n• Limited approval delegation capabilities.",
            "advanced": "• Configurable multi-level approval matrices.\n• Automated approval routing and tracking.\n• Basic approval delegation with audit trail.",
            "leading": "• Dynamic approval routing based on context.\n• Smart approval recommendations and bundling.\n• Advanced delegation with temporary authority transfer.",
            "emerging": "• AI-optimized approval workflows for efficiency.\n• Predictive approval orchestration based on patterns.\n• Self-managing approval ecosystems with ML optimization.",
        },
        {
            "qid": "6C", "stage": "Final Authorisation & Approval", 
            "process": "Limit Management & Control",
            "description": "Enforces transaction, daily, and cumulative limits for users, accounts, and payment channels.",
            "basic": "• Static limits applied uniformly.\n• Manual limit changes and overrides.\n• Limited visibility into limit consumption.",
            "advanced": "• Tiered limit structures by user/customer type.\n• Automated limit checking and enforcement.\n• Self-service limit management within boundaries.",
            "leading": "• Dynamic limit adjustment based on risk profile.\n• Real-time limit monitoring across channels.\n• Temporary limit increases with risk-based approval.",
            "emerging": "• AI-driven adaptive limits based on behavior.\n• Predictive limit management before threshold reached.\n• Self-optimizing limit frameworks that adapt to usage patterns.",
        },
        {
            "qid": "6D", "stage": "Final Authorisation & Approval", 
            "process": "Non-Repudiation & Evidence Capture",
            "description": "Creates and maintains legally admissible evidence of authorization decisions, approvals, and payment instructions.",
            "basic": "• Basic logging of approval actions.\n• Manual evidence collection if disputed.\n• Limited audit trail for authorizations.",
            "advanced": "• Digital signatures for key approvals.\n• Centralized audit repository with search.\n• Standardized evidence capture formats.",
            "leading": "• Cryptographic proof of authorization events.\n• Complete chain-of-evidence for all approvals.\n• Tamper-proof audit trail with third-party verification.",
            "emerging": "• Blockchain-based immutable authorization records.\n• Zero-knowledge proofs for privacy-preserving evidence.\n• Self-verifying authorization ecosystems with distributed trust.",
        },
        
        # Stage 7: Message Generation & Transformation
        {
            "qid": "7A", "stage": "Message Generation & Transformation", 
            "process": "Format Creation & Mapping",
            "description": "Transforms internal payment data into the appropriate message format for the target payment network or channel.",
            "basic": "• Manual message formatting and checking.\n• Limited format support (MT only).\n• Hard-coded transformation logic.",
            "advanced": "• Automated format creation and validation.\n• Support for major formats (MT, MX, ISO20022).\n• Configurable mapping rules by payment type.",
            "leading": "• Dynamic format selection and optimization.\n• Comprehensive format library with version control.\n• Intelligent mapping with context-aware transformations.",
            "emerging": "• AI-driven format optimization and auto-correction.\n• Self-adapting mappers for new message versions.\n• Format-agnostic processing with intelligent adapters.",
        },
        {
            "qid": "7B", "stage": "Message Generation & Transformation", 
            "process": "Message Enrichment",
            "description": "Adds required supplementary data elements, reference codes, and metadata to payment messages.",
            "basic": "• Minimal enrichment with required fields only.\n• Manual lookup of supplementary data.\n• Static reference code assignment.",
            "advanced": "• Automated data lookup and enrichment.\n• Reference data management system.\n• Configurable enrichment rules by message type.",
            "leading": "• Dynamic enrichment based on payment context.\n• Real-time reference data integration.\n• Intelligent data enhancement for optimal routing.",
            "emerging": "• AI-powered semantic enrichment for context.\n• Predictive data enhancement for downstream needs.\n• Self-learning enrichment that improves over time.",
        },
        {
            "qid": "7C", "stage": "Message Generation & Transformation", 
            "process": "Data Transformation & Normalization",
            "description": "Standardizes data elements, handles character set conversions, and ensures data quality during transformation.",
            "basic": "• Basic character set handling.\n• Limited normalization capabilities.\n• Manual correction of transformation errors.",
            "advanced": "• Automated data cleansing and normalization.\n• Comprehensive character set support.\n• Error detection and handling during transformation.",
            "leading": "• Intelligent data quality management.\n• Adaptive normalization based on target requirements.\n• Multi-format compatibility with version awareness.",
            "emerging": "• AI-driven semantic data understanding.\n• Self-correcting transformation with learning capabilities.\n• Context-aware normalization with intent preservation.",
        },
        {
            "qid": "7D", "stage": "Message Generation & Transformation", 
            "process": "Validation & Error Handling",
            "description": "Validates message structure, content, and compliance with network standards before transmission.",
            "basic": "• Basic schema validation only.\n• Manual error resolution process.\n• Limited error diagnostics capabilities.",
            "advanced": "• Comprehensive validation against network standards.\n• Automated error categorization and routing.\n• Self-service repair tools for common issues.",
            "leading": "• Predictive validation with pre-submission correction.\n• Intelligent error resolution suggestions.\n• Learning system that reduces recurring errors.",
            "emerging": "• AI-powered message optimization and validation.\n• Self-healing messages with automatic correction.\n• Predictive error prevention before messages created.",
        },
        
        # Stage 8: Transmission, Clearing & ACK
        {
            "qid": "8A", "stage": "Transmission, Clearing & ACK", 
            "process": "Network Connectivity & Transport",
            "description": "Securely connects to payment networks, manages sessions, and ensures reliable message delivery.",
            "basic": "• Single connection method to limited networks.\n• Manual session management and monitoring.\n• Basic retry logic for failed transmissions.",
            "advanced": "• Multiple connectivity options and channels.\n• Automated session management.\n• Comprehensive error handling and retry logic.",
            "leading": "• Dynamic channel selection and optimization.\n• Real-time network performance monitoring.\n• Intelligent routing based on network conditions.",
            "emerging": "• Self-optimizing connectivity with predictive switching.\n• AI-driven network performance optimization.\n• Autonomous transport layer with self-healing capabilities.",
        },
        {
            "qid": "8B", "stage": "Transmission, Clearing & ACK", 
            "process": "Message Security & Encryption",
            "description": "Applies appropriate encryption, digital signatures, and security controls to protect payment messages in transit.",
            "basic": "• Basic TLS encryption only.\n• Static security configurations.\n• Limited key management capabilities.",
            "advanced": "• End-to-end encryption for sensitive data.\n• Comprehensive key management system.\n• Regular security rotation and updates.",
            "leading": "• Adaptive encryption based on message sensitivity.\n• Advanced digital signature and non-repudiation.\n• Real-time security posture monitoring.",
            "emerging": "• Quantum-resistant encryption methods.\n• Self-defending messages with threat intelligence.\n• AI-driven security optimization with zero trust.",
        },
        {
            "qid": "8C", "stage": "Transmission, Clearing & ACK", 
            "process": "Clearing Process Management",
            "description": "Monitors and manages the clearing process, including netting, position management, and liquidity optimization.",
            "basic": "• Basic clearing submission without optimization.\n• Manual position monitoring and management.\n• Limited visibility into clearing status.",
            "advanced": "• Automated clearing submission and tracking.\n• Real-time position monitoring.\n• Liquidity forecasting and management tools.",
            "leading": "• Intelligent clearing optimization for cost/speed.\n• Advanced position management with alerts.\n• Dynamic liquidity allocation across networks.",
            "emerging": "• AI-driven clearing optimization with predictive models.\n• Autonomous position management and rebalancing.\n• Self-optimizing liquidity management across systems.",
        },
        {
            "qid": "8D", "stage": "Transmission, Clearing & ACK", 
            "process": "Acknowledgment & Status Tracking",
            "description": "Captures, processes, and manages network acknowledgments and payment status messages.",
            "basic": "• Manual ACK checking and reconciliation.\n• Limited status visibility in operations systems.\n• Basic logging of network responses.",
            "advanced": "• Automated ACK processing and matching.\n• Status dashboard for operations teams.\n• Structured storage of payment status history.",
            "leading": "• Real-time status propagation across channels.\n• Comprehensive payment tracking with full visibility.\n• Proactive alerts for missing or delayed ACKs.",
            "emerging": "• Predictive status management before ACKs received.\n• AI-driven anomaly detection for unusual responses.\n• Self-resolving exception management for ACK issues.",
        },
        
        # Stage 9: Settlement & Funds Movement
        {
            "qid": "9A", "stage": "Settlement & Funds Movement", 
            "process": "Settlement Execution",
            "description": "Finalizes the payment and executes the actual movement of funds between accounts, banks, or central bank accounts.",
            "basic": "• Manual settlement initiation and confirmation.\n• Batch-based settlement processes only.\n• Limited settlement options and methods.",
            "advanced": "• Automated settlement execution and tracking.\n• Support for multiple settlement methods.\n• Real-time settlement status visibility.",
            "leading": "• Intelligent settlement method selection.\n• Advanced settlement optimization.\n• Integrated cross-border settlement capabilities.",
            "emerging": "• AI-driven optimal settlement path determination.\n• Predictive settlement with just-in-time funding.\n• Autonomous settlement with distributed ledger options.",
        },
        {
            "qid": "9B", "stage": "Settlement & Funds Movement", 
            "process": "Liquidity & Funding Management",
            "description": "Ensures sufficient funds are available for settlement and optimizes liquidity usage across payment channels and currencies.",
            "basic": "• Manual liquidity monitoring and management.\n• Static funding levels for settlement accounts.\n• Limited cross-currency liquidity capabilities.",
            "advanced": "• Automated liquidity monitoring with alerts.\n• Scheduled funding based on forecasts.\n• Basic liquidity optimization tools.",
            "leading": "• Dynamic funding based on real-time needs.\n• Cross-network liquidity optimization.\n• Sophisticated cash flow forecasting models.",
            "emerging": "• AI-driven autonomous liquidity management.\n• Predictive funding with minimal buffer requirements.\n• Self-optimizing cross-currency liquidity allocation.",
        },
        {
            "qid": "9C", "stage": "Settlement & Funds Movement", 
            "process": "Intraday Credit Management",
            "description": "Manages credit lines, overdrafts, and intraday borrowing to support payment settlement.",
            "basic": "• Fixed credit lines with manual monitoring.\n• Limited intraday credit optimization.\n• Reactive overdraft management.",
            "advanced": "• Automated credit utilization monitoring.\n• Scheduled credit line adjustments.\n• Proactive overdraft prevention alerts.",
            "leading": "• Dynamic credit allocation based on payment flows.\n• Real-time credit optimization across channels.\n• Advanced collateral management integration.",
            "emerging": "• AI-optimized credit utilization with minimal cost.\n• Predictive credit needs before payments arrive.\n• Self-managing credit ecosystem with learning capabilities.",
        },
        {
            "qid": "9D", "stage": "Settlement & Funds Movement", 
            "process": "Settlement Risk Management",
            "description": "Identifies, monitors, and mitigates risks related to settlement failure, delays, or discrepancies.",
            "basic": "• Manual risk assessment and monitoring.\n• Basic settlement failure handling.\n• Limited contingency options.",
            "advanced": "• Automated risk monitoring with thresholds.\n• Standard contingency procedures.\n• Settlement failure detection and alerts.",
            "leading": "• Real-time risk visualization and management.\n• Advanced contingency routing and options.\n• Proactive risk mitigation strategies.",
            "emerging": "• AI-driven settlement risk prediction and prevention.\n• Self-healing settlement processes for disruptions.\n• Autonomous risk mitigation with minimal disruption.",
        },
        
        # Stage 10: Reconciliation & Exceptions
        {
            "qid": "10A", "stage": "Reconciliation & Exceptions", 
            "process": "Transaction Reconciliation",
            "description": "Matches and reconciles payments across systems, accounts, and ledgers to ensure completeness and accuracy.",
            "basic": "• Manual reconciliation processes.\n• Batch-based matching with limited automation.\n• High touch resolution of breaks.",
            "advanced": "• Automated matching with rule-based logic.\n• Daily reconciliation across major systems.\n• Exception queues with prioritization.",
            "leading": "• Near real-time reconciliation processes.\n• Advanced matching algorithms with fuzzy logic.\n• Machine learning for break pattern recognition.",
            "emerging": "• Real-time continuous reconciliation.\n• AI-driven predictive matching before breaks occur.\n• Self-healing reconciliation with autonomous correction.",
        },
        {
            "qid": "10B", "stage": "Reconciliation & Exceptions", 
            "process": "Exception Detection & Classification",
            "description": "Identifies, categorizes, and prioritizes exceptions, errors, and unusual conditions requiring intervention.",
            "basic": "• Manual exception identification.\n• Basic categorization with limited detail.\n• Chronological processing without prioritization.",
            "advanced": "• Automated exception detection and classification.\n• Multi-dimensional categorization system.\n• Priority-based exception handling queues.",
            "leading": "• Pattern-based proactive exception detection.\n• Machine learning classification of complex cases.\n• Risk-weighted prioritization framework.",
            "emerging": "• AI-driven anomaly detection before explicit errors.\n• Predictive exception management with prevention.\n• Self-improving classification with minimal false positives.",
        },
        {
            "qid": "10C", "stage": "Reconciliation & Exceptions", 
            "process": "Resolution & Repair",
            "description": "Resolves exceptions through data correction, payment cancellation, returns, or other appropriate actions.",
            "basic": "• Manual investigation and resolution process.\n• Limited resolution options and templates.\n• High touch repairs with multiple handoffs.",
            "advanced": "• Guided resolution with standard procedures.\n• Semi-automated correction capabilities.\n• Workflow-driven repair with tracking.",
            "leading": "• Intelligent resolution recommendation engine.\n• Automated correction of common exceptions.\n• Self-service repair tools with guardrails.",
            "emerging": "• AI-driven autonomous resolution for most cases.\n• Predictive resolution before customer impact.\n• Self-optimizing repair strategies with learning capabilities.",
        },
        {
            "qid": "10D", "stage": "Reconciliation & Exceptions", 
            "process": "Customer Communication & Case Management",
            "description": "Manages customer notification, inquiries, and complaints related to payment exceptions or errors.",
            "basic": "• Manual customer outreach for exceptions.\n• Email-based case tracking.\n• Limited visibility of case status.",
            "advanced": "• Template-based customer notifications.\n• Dedicated case management system.\n• Service level tracking and reporting.",
            "leading": "• Personalized exception communication strategy.\n• Integrated omnichannel case management.\n• Proactive status updates throughout resolution.",
            "emerging": "• AI-driven contextual communication strategy.\n• Predictive case management before customer inquiry.\n• Self-resolving customer engagement with minimal friction.",
        },
        
        # Stage 11: Reporting, Analytics & Notifications
        {
            "qid": "11A", "stage": "Reporting, Analytics & Notifications", 
            "process": "Payment Status Notification",
            "description": "Provides timely updates to customers and stakeholders about payment status, completion, or exceptions.",
            "basic": "• Email-only notifications for major events.\n• Batch processing of notification events.\n• Limited notification content and options.",
            "advanced": "• Multi-channel notification delivery (email, SMS, app).\n• Near-real-time status updates for key events.\n• Configurable notification preferences.",
            "leading": "• Real-time push notifications across all channels.\n• Contextualized notifications with next steps.\n• Event-driven architecture for immediate updates.",
            "emerging": "• Predictive notifications before events occur.\n• AI-optimized channel and timing selection.\n• Interactive conversational notifications with resolution.",
        },
        {
            "qid": "11B", "stage": "Reporting, Analytics & Notifications", 
            "process": "Reporting & Business Intelligence",
            "description": "Provides insights, analytics, and reporting on payment activity, performance, and trends.",
            "basic": "• Static reports with manual generation.\n• Basic transaction listings without analytics.\n• Limited historical data availability.",
            "advanced": "• Scheduled reporting with standard dashboards.\n• Self-service report generation options.\n• Payment analytics with basic trending.",
            "leading": "• Real-time dashboards with drill-down capabilities.\n• Advanced analytics with pattern recognition.\n• Predictive forecasting and trend analysis.",
            "emerging": "• AI-driven autonomous insight generation.\n• Predictive analytics with action recommendations.\n• Natural language query interface for analytics.",
        },
        {
            "qid": "11C", "stage": "Reporting, Analytics & Notifications", 
            "process": "Cash Management & Forecasting",
            "description": "Provides tools and insights for managing cash positions, forecasting payment flows, and optimizing liquidity.",
            "basic": "• Basic cash position reporting.\n• Manual forecasting with spreadsheets.\n• Limited historical analysis capabilities.",
            "advanced": "• Daily cash position dashboards.\n• Automated forecasting based on scheduled payments.\n• Historical pattern analysis for planning.",
            "leading": "• Real-time cash position visualization.\n• Advanced forecasting with multiple scenarios.\n• Machine learning for payment pattern prediction.",
            "emerging": "• AI-driven autonomous cash optimization.\n• Predictive cash forecasting with high accuracy.\n• Self-adjusting models that learn from outcomes.",
        },
        {
            "qid": "11D", "stage": "Reporting, Analytics & Notifications", 
            "process": "Data Visualization & Exploration",
            "description": "Provides intuitive visual tools for exploring payment data, identifying patterns, and gaining insights.",
            "basic": "• Static report tables with limited graphics.\n• Pre-defined views without customization.\n• Manual data extraction for analysis.",
            "advanced": "• Interactive dashboards with filtering.\n• Standard visualization library.\n• Export capabilities for further analysis.",
            "leading": "• Advanced visualization suite with drill-down.\n• Self-service visualization creation.\n• Cross-system data exploration capabilities.",
            "emerging": "• AI-recommended visualizations based on context.\n• Natural language generation of insights.\n• Augmented analytics with automated pattern discovery.",
        },
        
        # Stage 12: Audit, Archival & Compliance
        {
            "qid": "12A", "stage": "Audit, Archival & Compliance", 
            "process": "Payment Data Archival",
            "description": "Securely stores payment data, ensuring it meets retention requirements while maintaining accessibility for queries and audits.",
            "basic": "• Manual archiving processes with basic storage.\n• Limited searchability of archived data.\n• Basic retention period management.",
            "advanced": "• Automated archiving with indexing.\n• Structured storage with query capabilities.\n• Configurable retention policies by data type.",
            "leading": "• Intelligent archiving with full-text search.\n• Tiered storage optimization for cost/access.\n• Integrated lifecycle management with alerts.",
            "emerging": "• AI-driven autonomous archival optimization.\n• Predictive access patterns for retrieval optimization.\n• Blockchain-anchored immutable audit records.",
        },
        {
            "qid": "12B", "stage": "Audit, Archival & Compliance", 
            "process": "Audit Trail & Logging",
            "description": "Maintains comprehensive logs of all actions, decisions, and system events related to payment processing.",
            "basic": "• Basic system logs with limited detail.\n• Manual audit trail extraction and review.\n• Minimal user action logging.",
            "advanced": "• Centralized logging with structured data.\n• User action audit trails with identity.\n• Searchable audit history with filtering.",
            "leading": "• Complete end-to-end action traceability.\n• Tamper-evident logging mechanisms.\n• Advanced correlation across systems and events.",
            "emerging": "• Blockchain-based immutable audit trails.\n• AI-powered anomaly detection in audit patterns.\n• Self-verifying audit ecosystems with cryptographic proof.",
        },
        {
            "qid": "12C", "stage": "Audit, Archival & Compliance", 
            "process": "Regulatory Reporting",
            "description": "Creates and submits required regulatory reports related to payment processing, ensuring accuracy and timeliness.",
            "basic": "• Manual report compilation and submission.\n• Limited validation before submission.\n• Static reporting templates with minimal updates.",
            "advanced": "• Automated report generation from templates.\n• Pre-submission validation and checks.\n• Scheduled generation with approval workflow.",
            "leading": "• Dynamic regulatory report generation.\n• Real-time data validation and enrichment.\n• Cross-regulation optimization and deduplication.",
            "emerging": "• AI-driven regulatory interpretation and adaptation.\n• Continuous compliance monitoring and reporting.\n• Predictive regulatory change management.",
        },
        {
            "qid": "12D", "stage": "Audit, Archival & Compliance", 
            "process": "Legal & Compliance Controls",
            "description": "Ensures payment processes adhere to relevant laws, regulations, and internal policies through systematic controls.",
            "basic": "• Manual compliance checks and attestations.\n• Static control framework with limited updates.\n• Paper-based evidence collection and storage.",
            "advanced": "• Automated control monitoring with alerts.\n• Regular compliance assessment cycles.\n• Digital evidence collection and repository.",
            "leading": "• Continuous control monitoring in real-time.\n• Integrated compliance risk assessment.\n• Automated evidence collection with validation.",
            "emerging": "• AI-driven adaptive compliance controls.\n• Predictive compliance with regulatory intelligence.\n• Self-assessing control framework with minimal gaps.",
        }
    ]
    return data
