import pandas as pd

# This file contains the data for business outcomes and maturity descriptions

# Define option descriptions
OPTION_DESCRIPTIONS = {
    "Basic": {
        "value": 0,
        "description": "Minimal functionality, often manual processes, requiring significant user effort and offering limited capabilities."
    },
    "Advanced": {
        "value": 0.33,
        "description": "Standard industry functionality with some automation and integration, providing reliable but not exceptional service."
    },
    "Leading": {
        "value": 0.66,
        "description": "Above average capabilities with significant automation, integration, and optimization, offering competitive advantage."
    },
    "Emerging": {
        "value": 1.0,
        "description": "Cutting-edge, innovative capabilities leveraging AI, machine learning, and advanced technologies to deliver exceptional service."
    }
}

# Convert process details into dataframe
def load_process_details():
    data = [
        # Stage 1: Payment Initiation & Data Capture
        {
            "qid": "1A", "stage": "Payment Initiation & Data Capture", 
            "process": "Channel Access & Log-In",
            "description": "Provides the customer or corporate user with secure entry points to initiate payments—mobile app, web portal, POS, wallet or ERP/TMS integration, bulk-file upload or APIs/host-to-host.",
            "basic": "• Multiple siloed channels with separate credentials (e.g. branch login, web login, mobile login).\n• No single-sign-on; users must reauthenticate per channel.\n• Slow password/PIN flows, little automation in session management.",
            "advanced": "• Centralized IAM with single-sign-on across channels.\n• Persistent sessions via secure cookies or device trust.\n• Basic adaptive MFA (e.g. step-up for high-value payments).",
            "leading": "• Fully unified CIAM platform: SSO, OAuth2/OIDC, device fingerprinting.\n• Contextual authentication (risk-based MFA triggered automatically).\n• API-first design so third-party apps (ERP, fintech partners) share the same login flow.",
            "emerging": "• Passwordless with behavioral biometrics.\n• AI-driven fraud prevention in login (behavioral biometrics, continuous authentication).\n• Decentralized identity (DID) using verifiable credentials for corporate users.",
        },
        {
            "qid": "1B", "stage": "Payment Initiation & Data Capture", 
            "process": "Payment Setup",
            "description": "The screen or API call where payer enters or uploads the payment details: retail single-payment UI or corporate bulk file (e.g. payroll).",
            "basic": "• Manual UI form for single payment with limited reuse of payees.\n• Corporate uses flat-file templates via SFTP.\n• No intelligent defaults; all fields must be typed.",
            "advanced": "• Pre-populated beneficiary lists, autocomplete of recurring payees.\n• Corporate B2B portal supports CSV/ISO 20022 XML upload with template validation.\n• \"Save as draft\" workflows for approval queues.",
            "leading": "• Guided UI with next-best-action suggestions (AI-driven) for payees/amounts.\n• Bulk template import via API, with dynamic loading of corporate ACH/RTGS parameters.\n• Auto-grouping of bulk payments by payee or category for faster entry.",
            "emerging": "• Conversational-UI or voice-driven payment setup.\n• Zero-touch invoice-to-pay: AI ingests PDF invoices, auto-creates payment batches.\n• Real-time integrations with ERP to auto-trigger payments on invoice receipt.",
        },
        {
            "qid": "1C", "stage": "Payment Initiation & Data Capture", 
            "process": "Data Entry & Input Validation",
            "description": "Ensures the data entered is syntactically & semantically correct—format checks (IBAN, BIC), mandatory fields, and optional real-time lookups (account status, card BIN).",
            "basic": "• Basic form validation with generic error messages.\n• Manual correction loops with full page refresh.\n• No contextual help or inline validation.",
            "advanced": "• Inline validation with field-specific error messages.\n• Format detection & normalization (e.g. auto-format card numbers).\n• Address verification against postal database.",
            "leading": "• Dynamic validation based on payment type & destination country.\n• Beneficiary name & account validation in real-time.\n• PAN/CVV validation against card BIN database.",
            "emerging": "• AI-powered predictive field completion & error correction.\n• Real-time IBAN lookup with beneficiary confirmation API.\n• ML anomaly detection to flag unusual payment characteristics.",
        },
        {
            "qid": "1D", "stage": "Payment Initiation & Data Capture", 
            "process": "Submission & Order Creation",
            "description": "Captures the completed payment order, creates the payment record, and hands off to downstream processing—confirms submission & provides reference number.",
            "basic": "• Batch processing with end-of-day execution.\n• No real-time feedback or status tracking.\n• Manual record creation & tracking.",
            "advanced": "• Real-time order creation with immediate confirmation.\n• Digital receipt with unique reference number.\n• Payment status tracking in customer portal.",
            "leading": "• Event streaming architecture with guaranteed order capture.\n• Multi-channel payment status notifications.\n• Payment history searchable by multiple parameters (date, amount, payee).",
            "emerging": "• Zero-latency distributed ledger recording.\n• Blockchain-based immutable payment record.\n• Full payment lifecycle visibility with real-time status changes.",
        },
        
        # Stage 2: Authentication & Identity Validation
        {
            "qid": "2A", "stage": "Authentication & Identity Validation", 
            "process": "Primary Authentication",
            "description": "Confirms the identity of the payment initiator through username/password challenge, biometrics, passkeys, or other credentials.",
            "basic": "• Simple username/password authentication.\n• No biometric options, only PIN/password.\n• Long session timeout requiring frequent re-auth.",
            "advanced": "• Industry-standard 2FA (SMS OTP, email links).\n• Basic biometric options (fingerprint, face).\n• Security questions for high-risk actions.",
            "leading": "• FIDO2/WebAuthn support with token-based auth.\n• Multiple biometric options on all channels.\n• Intelligent session management based on risk.",
            "emerging": "• Passwordless with passkeys for all channels.\n• Behavioral biometrics as primary auth factor.\n• Continuous authentication throughout payment journey.",
        },
        {
            "qid": "2B", "stage": "Authentication & Identity Validation", 
            "process": "Multi-Factor Authentication",
            "description": "Adds additional verification factors when required by transaction risk, compliance requirements, or to ensure non-repudiation.",
            "basic": "• SMS one-time codes as only second factor.\n• No risk-based MFA triggers.\n• Blanket approach requiring same MFA for all payments.",
            "advanced": "• App-based authenticator options.\n• Basic risk rules trigger step-up auth.\n• Configurable MFA thresholds based on amount.",
            "leading": "• Multiple authenticator options (TOTP, push notifications).\n• Out-of-band verification through multiple channels.\n• Context-aware adaptive authentication.",
            "emerging": "• Presence-based silent authentication.\n• Biometric MFA with liveness detection.\n• AI-driven continuous risk assessment.",
        },
        {
            "qid": "2C", "stage": "Authentication & Identity Validation", 
            "process": "Corporate Authorization",
            "description": "For business accounts, validates the initiator has proper entitlements, mandate & signing authority, and enforces payment limits by role & amount.",
            "basic": "• Static role-based access control.\n• Manual entitlement verification.\n• No integration with corporate hierarchy data.",
            "advanced": "• Automated limit checks during initiation.\n• Pre-defined approval workflows.\n• Role-based dashboards & controls.",
            "leading": "• Dynamic mandate checking against corporate structure.\n• Real-time signature verification against mandate database.\n• Complex approval matrix support (multiple approvers by criteria).",
            "emerging": "• Decentralized identity verification with VC/blockchain.\n• Algorithm-based smart approval routing.\n• Integration with corporate governance systems.",
        },
        {
            "qid": "2D", "stage": "Authentication & Identity Validation", 
            "process": "Session Security",
            "description": "Prevents session hijacking, maintains secure payment context, and protects the authenticated state from theft or replay attacks.",
            "basic": "• Basic cookie-based sessions.\n• Short timeouts with full re-auth required.\n• No detection of session anomalies.",
            "advanced": "• Encrypted session tokens with regular rotation.\n• Session binding to IP address.\n• Automatic logout on inactivity.",
            "leading": "• Advanced device fingerprinting.\n• Certificate pinning for mobile apps.\n• Session continuity across channels.",
            "emerging": "• Zero trust architecture with continuous validation.\n• Real-time risk scoring of session behaviors.\n• Quantum-resistant session cryptography.",
        },
        
        # Stage 3: Pre-Submission Validation
        {
            "qid": "3A", "stage": "Pre-Submission Validation", 
            "process": "Format & Completeness Checks",
            "description": "Validates all required fields are present, properly formatted, and meet the criteria for the specific payment type, channel, and destination.",
            "basic": "• Basic required field validation.\n• Generic error messages.\n• Limited format validation (length, character type).",
            "advanced": "• Payment-type specific validation rules.\n• Clear error identification with correction guidance.\n• Format standardization before submission.",
            "leading": "• Dynamic field requirements based on payment context.\n• Real-time field-level validation for all inputs.\n• Format transformation & normalization.",
            "emerging": "• AI-based predictive validation of complex fields.\n• Metadata enrichment from multiple sources.\n• Semantic validation of payment purpose.",
        },
        {
            "qid": "3B", "stage": "Pre-Submission Validation", 
            "process": "Business Rule Enforcement",
            "description": "Checks payment against business policies like daily limits, duplicate detection, allowed destinations, frequency caps, and balance requirements.",
            "basic": "• Static hard-coded business rules.\n• Basic duplicate payment detection.\n• Manual balance checks.",
            "advanced": "• Centralized rules engine with versioning.\n• Automated funds availability verification.\n• Real-time limit monitoring.",
            "leading": "• Dynamic rules triggered by contextual factors.\n• ML-based duplicate detection (fuzzy matching).\n• Cross-channel rule consistency.",
            "emerging": "• Self-optimizing rules based on payment patterns.\n• Predictive cash flow verification.\n• Natural language policy definition.",
        },
        {
            "qid": "3C", "stage": "Pre-Submission Validation", 
            "process": "Preliminary Compliance Screening",
            "description": "Performs initial screening of payment against sanctions lists, high-risk countries, and suspicious patterns before committing to the payment flow.",
            "basic": "• Basic screening against outdated sanctions lists.\n• No real-time screening during payment initiation.\n• Binary pass/fail with manual review process.",
            "advanced": "• Daily-updated screening lists.\n• Real-time initial screening during payment entry.\n• Name matching with fuzzy logic.",
            "leading": "• API-connected sanctions screening service.\n• Risk-based screening depth based on payment profile.\n• Automated resolution of common false positives.",
            "emerging": "• Real-time multi-source screening with AI detection.\n• Behavioral/transactional pattern analysis.\n• Automated regulatory update implementation.",
        },
        {
            "qid": "3D", "stage": "Pre-Submission Validation", 
            "process": "Risk-Based Decisions",
            "description": "Applies risk-based logic to route payments for additional verification, determine authentication needs, or enable straight-through processing.",
            "basic": "• Binary risk decisions (approve/reject).\n• Manual risk assessment processes.\n• Limited risk factors considered.",
            "advanced": "• Multi-tier risk classification system.\n• Basic scoring model for payment risk.\n• Risk-based routing to verification queues.",
            "leading": "• Dynamic risk profiling using multiple data points.\n• Real-time payment context analysis.\n• ML/statistical models for risk calculation.",
            "emerging": "• AI-driven real-time risk scoring engine.\n• Behavior-based anomaly detection.\n• Continuous learning from fraud outcomes.",
        },
        
        # Stage 4: Payment Orchestration & Routing
        {
            "qid": "4A", "stage": "Payment Orchestration & Routing", 
            "process": "Routing Selection",
            "description": "Determines the optimal payment network, channel, or rail based on payment attributes, preferences, costs, and availability.",
            "basic": "• Fixed routing rules based on payment type only.\n• Manual selection of routing channels.\n• No optimization for cost or speed.",
            "advanced": "• Static rule-based routing optimization.\n• Cost and timeline consideration.\n• Alternate routing for failures.",
            "leading": "• Dynamic routing based on multiple factors (cost, speed, reliability).\n• Real-time network availability monitoring.\n• Analytics-driven route selection.",
            "emerging": "• AI-optimized routing decisions across all factors.\n• Predictive outage prevention with auto-rerouting.\n• Customer preference-aware routing.",
        },
        {
            "qid": "4B", "stage": "Payment Orchestration & Routing", 
            "process": "Payment Orchestration",
            "description": "Coordinates the sequence of payment-related activities, manages state transitions, handles timeouts, and retries failed operations.",
            "basic": "• Basic linear payment processing flow.\n• Manual handling of failures and exceptions.\n• Limited visibility into payment state.",
            "advanced": "• Structured workflows with defined states.\n• Automated retry mechanisms.\n• Basic exception handling.",
            "leading": "• Event-driven architecture with parallel processing.\n• Sophisticated state machine implementation.\n• Configurable workflow orchestration.",
            "emerging": "• AI-driven process optimization.\n• Self-healing payment flows.\n• Dynamic orchestration based on real-time conditions.",
        },
        {
            "qid": "4C", "stage": "Payment Orchestration & Routing", 
            "process": "Fee Calculation & Disclosure",
            "description": "Calculates applicable transaction fees based on payment type, destination, priority, and customer agreements, then presents them to the user.",
            "basic": "• Static fee schedules.\n• Basic fee calculation.\n• Limited fee transparency.",
            "advanced": "• Dynamic fee calculation based on multiple factors.\n• Clear fee disclosure before payment initiation.\n• Fee optimization options for customers.",
            "leading": "• Real-time fee comparison across routes.\n• Intelligent fee optimization suggestions.\n• Personalized fee schedules based on relationship.",
            "emerging": "• AI-driven predictive fee optimization.\n• Integrated loyalty/rewards consideration.\n• Real-time competitor fee benchmarking.",
        },
        {
            "qid": "4D", "stage": "Payment Orchestration & Routing", 
            "process": "Network/Partner Connectivity",
            "description": "Maintains connections to payment networks, messaging gateways, and partner systems, handling protocol translations and format conversions.",
            "basic": "• Point-to-point integrations with limited partners.\n• Batch-file based connections.\n• Manual monitoring of connectivity.",
            "advanced": "• API-based connectivity with major partners.\n• Standardized integration patterns.\n• Automated connectivity monitoring.",
            "leading": "• Real-time API ecosystem with broad coverage.\n• Multi-protocol gateway management.\n• Self-service partner onboarding.",
            "emerging": "• Intelligent API management with traffic optimization.\n• Blockchain/DLT network participation.\n• AI-driven connectivity health prediction.",
        },
                
        # Stage 5: Risk, Fraud & Compliance
        {
            "qid": "5A", "stage": "Risk, Fraud & Compliance", 
            "process": "Fraud Detection & Scoring",
            "description": "Identifies potentially fraudulent payments through rule-based and machine learning models that analyze payment attributes, behavior patterns, and historical data.",
            "basic": "• Basic rule-based fraud checks.\n• Manual fraud investigation.\n• Limited data sources for fraud detection.",
            "advanced": "• Real-time fraud screening with scoring.\n• Dedicated fraud management system.\n• Multiple data points for fraud assessment.",
            "leading": "• Advanced ML models for fraud detection.\n• Behavioral biometrics analysis.\n• Dynamic rule optimization based on outcomes.",
            "emerging": "• AI-driven fraud prevention with continuous learning.\n• Federated fraud intelligence.\n• Real-time pattern recognition across channels.",
        },
        {
            "qid": "5B", "stage": "Risk, Fraud & Compliance", 
            "process": "Sanctions & AML Screening",
            "description": "Screens payment against sanctions lists, politically exposed persons (PEPs), and anti-money laundering (AML) rules to ensure regulatory compliance.",
            "basic": "• Manual sanctions screening.\n• Basic compliance checks.\n• Limited list coverage.",
            "advanced": "• Automated screening against major lists.\n• Regular list updates.\n• Basic name-matching algorithms.",
            "leading": "• Real-time screening against comprehensive databases.\n• Advanced name-matching with contextual analysis.\n• Integration with global compliance intelligence.",
            "emerging": "• AI-driven compliance risk assessment.\n• Behavioral pattern analysis for money laundering.\n• Predictive compliance risk scoring.",
        },
        {
            "qid": "5C", "stage": "Risk, Fraud & Compliance", 
            "process": "Risk Management",
            "description": "Assesses and manages payment risk through exposure monitoring, limit enforcement, and risk-based authentication and approval requirements.",
            "basic": "• Basic transaction limits.\n• Manual risk assessment.\n• Limited risk mitigation options.",
            "advanced": "• Multi-tier limit structure.\n• Automated exposure tracking.\n• Risk-based approval workflows.",
            "leading": "• Dynamic limit management.\n• Real-time exposure monitoring.\n• Contextual risk-based controls.",
            "emerging": "• AI-driven risk prediction and prevention.\n• Behavioral risk profiling.\n• Dynamic risk-based transaction handling.",
        },
        {
            "qid": "5D", "stage": "Risk, Fraud & Compliance", 
            "process": "Case Management & Investigation",
            "description": "Manages the workflow for investigating flagged payments, collecting evidence, making decisions, and documenting compliance actions.",
            "basic": "• Manual case tracking.\n• Siloed investigation processes.\n• Limited documentation.",
            "advanced": "• Structured case management system.\n• Standard investigation workflows.\n• Digital evidence collection.",
            "leading": "• Integrated case management with full workflow.\n• Automated evidence gathering.\n• Advanced analytics for case resolution.",
            "emerging": "• AI-assisted investigation with recommendation engine.\n• Predictive case scoring and prioritization.\n• Natural language processing for documentation.",
        },
        
        # Stage 6: Final Authorisation & Approval
        {
            "qid": "6A", "stage": "Final Authorisation & Approval", 
            "process": "Payment Approval Workflows",
            "description": "Manages the review and approval process for payments requiring additional authorization from supervisors, compliance, or other stakeholders.",
            "basic": "• Manual approval workflows.\n• Paper-based signatures or authorizations.\n• Limited tracking of approval status.",
            "advanced": "• Digital approval workflows.\n• Mobile approval capabilities.\n• Real-time approval status tracking.",
            "leading": "• Intelligent approval routing based on context.\n• Multi-channel approval options.\n• Delegation and proxy approval support.",
            "emerging": "• AI-optimized approval workflows.\n• Risk-adaptive approval requirements.\n• Biometric/blockchain-based approval validation.",
        },
        {
            "qid": "6B", "stage": "Final Authorisation & Approval", 
            "process": "Funds Availability Verification",
            "description": "Confirms that sufficient funds or credit are available for the payment, considering holds, pending transactions, and intraday positions.",
            "basic": "• Point-in-time balance checks.\n• Manual overdraft decisions.\n• Limited consideration of pending items.",
            "advanced": "• Real-time balance verification.\n• Automated overdraft handling.\n• Consideration of pending debits.",
            "leading": "• Predictive cash flow analysis.\n• Dynamic credit line utilization.\n• Cross-account pooling for availability.",
            "emerging": "• AI-driven liquidity optimization.\n• Real-time payment scheduling for optimal timing.\n• Proactive liquidity alerts and recommendations.",
        },
        {
            "qid": "6C", "stage": "Final Authorisation & Approval", 
            "process": "Posting & Ledger Update",
            "description": "Records the payment transaction in bank ledgers, updates balances, and applies accounting entries to customer accounts.",
            "basic": "• Batch-based posting.\n• End-of-day processing.\n• Limited real-time visibility.",
            "advanced": "• Near-real-time posting.\n• Immediate balance updates.\n• Intraday statement availability.",
            "leading": "• Real-time distributed ledger updates.\n• Split-second posting confirmation.\n• Cross-system synchronization.",
            "emerging": "• Blockchain/DLT-based immutable ledger.\n• AI reconciliation and error prevention.\n• Real-time multi-currency/asset accounting.",
        },
        {
            "qid": "6D", "stage": "Final Authorisation & Approval", 
            "process": "Release Management",
            "description": "Controls the final release of payments to the network after all approvals, checks, and authorizations are completed.",
            "basic": "• Manual payment release.\n• Batch-based submission windows.\n• Limited release criteria.",
            "advanced": "• Automated release based on schedule.\n• Release queues with prioritization.\n• Pre-release validation checks.",
            "leading": "• Dynamic release optimization.\n• Real-time network awareness.\n• Intelligent release timing for cost/speed optimization.",
            "emerging": "• AI-driven release optimization.\n• Predictive outage avoidance.\n• SLA-driven automatic routing selection for release.",
        },
        
        # Stage 7: Message Generation & Transformation
        {
            "qid": "7A", "stage": "Message Generation & Transformation", 
            "process": "Payment Formatting",
            "description": "Transforms internal payment data into the required format for the selected payment network or channel (SWIFT MT, ISO 20022, domestic formats).",
            "basic": "• Manual format mapping.\n• Limited format support.\n• Static transformation rules.",
            "advanced": "• Automated format transformation.\n• Support for major payment formats.\n• Validation before transmission.",
            "leading": "• Dynamic format selection and mapping.\n• Comprehensive format library.\n• Intelligent data enrichment during formatting.",
            "emerging": "• AI-driven format optimization.\n• Automatic new format adaptation.\n• Semantic understanding of payment context for mapping.",
        },
        {
            "qid": "7B", "stage": "Message Generation & Transformation", 
            "process": "Data Enrichment",
            "description": "Adds required data elements from reference data, enhances payment with additional information, and ensures compliance with format specifications.",
            "basic": "• Basic mandatory field population.\n• Manual data lookup and enrichment.\n• Limited reference data sources.",
            "advanced": "• Automated reference data lookup.\n• Multiple data sources for enrichment.\n• Validation of enriched data.",
            "leading": "• Intelligent context-based enrichment.\n• Dynamic reference data management.\n• Advanced validation with error correction.",
            "emerging": "• AI-powered predictive data completion.\n• External data integration for enrichment.\n• Self-learning enrichment models.",
        },
        {
            "qid": "7C", "stage": "Message Generation & Transformation", 
            "process": "Message Validation",
            "description": "Validates payment messages against network/scheme rules, format specifications, and syntax requirements before transmission.",
            "basic": "• Basic syntax checking.\n• Limited validation rules.\n• Manual error correction.",
            "advanced": "• Network-specific validation rules.\n• Automated error detection.\n• Guided error resolution.",
            "leading": "• Comprehensive validation against all standards.\n• Intelligent error correction suggestions.\n• Real-time validation against network changes.",
            "emerging": "• AI-powered validation with auto-correction.\n• Predictive validation before submission.\n• Self-learning validation rule updates.",
        },
        {
            "qid": "7D", "stage": "Message Generation & Transformation", 
            "process": "Message Repair",
            "description": "Handles exception cases where messages fail validation, providing tools to correct errors and resubmit without manual reentry.",
            "basic": "• Manual repair processes.\n• Full reentry for failed messages.\n• Limited tracking of repair history.",
            "advanced": "• Guided repair interface.\n• Repair workflow management.\n• Audit trail of changes.",
            "leading": "• Intelligent repair suggestions.\n• Automated repairs for common errors.\n• Root cause analysis of recurring issues.",
            "emerging": "• AI-driven repair automation.\n• Predictive error prevention.\n• Self-healing message generation.",
        },
        
        # Stage 8: Transmission, Clearing & ACK
        {
            "qid": "8A", "stage": "Transmission, Clearing & ACK", 
            "process": "Network Connectivity",
            "description": "Manages secure connections to payment networks, messaging services, and clearing houses with proper authentication and security.",
            "basic": "• Limited network connections.\n• Manual connection management.\n• Basic security controls.",
            "advanced": "• Secure network infrastructure.\n• Automated connection monitoring.\n• Redundant connections for critical networks.",
            "leading": "• Real-time network health monitoring.\n• Automated failover capabilities.\n• Advanced encryption and security.",
            "emerging": "• AI-driven network optimization.\n• Predictive outage prevention.\n• Quantum-resistant encryption.",
        },
        {
            "qid": "8B", "stage": "Transmission, Clearing & ACK", 
            "process": "Transmission Monitoring",
            "description": "Tracks the status of payment transmissions, monitors for acknowledgments, and handles communication exceptions.",
            "basic": "• Manual transmission tracking.\n• Basic error notifications.\n• Limited visibility into transmission state.",
            "advanced": "• Automated transmission tracking.\n• Real-time status dashboards.\n• Proactive alerting for issues.",
            "leading": "• End-to-end payment tracking.\n• Predictive transmission analysis.\n• Advanced exception handling.",
            "emerging": "• AI-powered transmission optimization.\n• Predictive issue detection and resolution.\n• Self-healing transmission processes.",
        },
        {
            "qid": "8C", "stage": "Transmission, Clearing & ACK", 
            "process": "Clearing Process Management",
            "description": "Manages the clearing process with counterparties, networks, or central infrastructure, handling cycles, cut-offs, and settlement instructions.",
            "basic": "• Manual clearing process management.\n• Basic cut-off monitoring.\n• Limited visibility into clearing status.",
            "advanced": "• Automated clearing schedule management.\n• Real-time cut-off alerts.\n• Digital clearing process dashboard.",
            "leading": "• Dynamic clearing optimization.\n• Advanced liquidity management for clearing.\n• Real-time settlement tracking.",
            "emerging": "• AI-driven clearing optimization.\n• Predictive settlement management.\n• Distributed ledger-based real-time clearing.",
        },
        {
            "qid": "8D", "stage": "Transmission, Clearing & ACK", 
            "process": "Acknowledgment Processing",
            "description": "Captures, processes, and manages acknowledgments, rejections, and other responses from networks, ensuring proper handling of each status.",
            "basic": "• Manual acknowledgment tracking.\n• Basic status updates.\n• Limited response handling capabilities.",
            "advanced": "• Automated acknowledgment processing.\n• Structured workflow for rejections.\n• Real-time status updates.",
            "leading": "• Intelligent response handling.\n• Proactive rejection management.\n• Advanced retry strategies.",
            "emerging": "• AI-driven response optimization.\n• Predictive rejection prevention.\n• Self-learning improvement of success rates.",
        },
        
        # Stage 9: Settlement & Funds Movement
        {
            "qid": "9A", "stage": "Settlement & Funds Movement", 
            "process": "Settlement Execution",
            "description": "Executes the final settlement between banks, including central bank money movements, correspondent banking entries, or internal book transfers.",
            "basic": "• Manual settlement processing.\n• Batch-based settlement.\n• Limited settlement options.",
            "advanced": "• Automated settlement execution.\n• Multiple settlement methods.\n• Real-time settlement status.",
            "leading": "• Dynamic settlement optimization.\n• Advanced nostro/vostro management.\n• Integrated liquidity considerations.",
            "emerging": "• AI-driven settlement route optimization.\n• Real-time gross settlement integration.\n• Blockchain/DLT-based settlement capabilities.",
        },
        {
            "qid": "9B", "stage": "Settlement & Funds Movement", 
            "process": "Nostro/Vostro Management",
            "description": "Manages correspondent accounts, monitors balances, and optimizes usage of nostro accounts for international payments.",
            "basic": "• Manual nostro account monitoring.\n• Basic reconciliation processes.\n• Limited optimization of nostro usage.",
            "advanced": "• Automated nostro balance tracking.\n• Daily reconciliation and forecasting.\n• Threshold alerts for nostro accounts.",
            "leading": "• Real-time nostro position management.\n• Advanced forecasting and optimization.\n• Integrated FX and liquidity management.",
            "emerging": "• AI-powered nostro optimization.\n• Predictive balance management.\n• Blockchain-based nostro reconciliation.",
        },
        {
            "qid": "9C", "stage": "Settlement & Funds Movement", 
            "process": "Liquidity Management",
            "description": "Optimizes intraday liquidity, manages funding, and coordinates timing of large payments to minimize liquidity requirements.",
            "basic": "• Basic intraday liquidity monitoring.\n• Manual funding decisions.\n• Limited payment timing coordination.",
            "advanced": "• Automated liquidity monitoring.\n• Scheduled funding operations.\n• Payment queue management for liquidity.",
            "leading": "• Real-time liquidity optimization.\n• Dynamic payment sequencing.\n• Advanced forecasting and modeling.",
            "emerging": "• AI-driven liquidity optimization.\n• Predictive funding management.\n• Self-learning payment schedulers.",
        },
        {
            "qid": "9D", "stage": "Settlement & Funds Movement", 
            "process": "Settlement Risk Management",
            "description": "Manages settlement risk through netting, position limits, collateral management, and monitoring counterparty exposures.",
            "basic": "• Basic counterparty limits.\n• Manual risk assessment.\n• Limited netting capabilities.",
            "advanced": "• Automated exposure monitoring.\n• Structured netting processes.\n• Regular limit reviews and adjustments.",
            "leading": "• Real-time exposure management.\n• Dynamic limit adjustment.\n• Advanced netting optimization.",
            "emerging": "• AI-driven risk prediction and mitigation.\n• Blockchain-based smart contracts for settlement.\n• Tokenized collateral management.",
        },
        
        # Stage 10: Reconciliation & Exceptions
        {
            "qid": "10A", "stage": "Reconciliation & Exceptions", 
            "process": "Transaction Reconciliation",
            "description": "Matches and reconciles payment transactions across systems, identifying and resolving unmatched items and discrepancies.",
            "basic": "• Manual reconciliation processes.\n• Basic matching logic.\n• Limited automation of exception handling.",
            "advanced": "• Automated reconciliation with rules engine.\n• Exception workflow management.\n• Digital audit trails.",
            "leading": "• Real-time reconciliation capabilities.\n• Advanced matching algorithms.\n• Predictive exception identification.",
            "emerging": "• AI-powered reconciliation with auto-resolution.\n• Machine learning for pattern recognition.\n• Blockchain-based immutable transaction records.",
        },
        {
            "qid": "10B", "stage": "Reconciliation & Exceptions", 
            "process": "Exception Handling",
            "description": "Manages exceptions, returns, cancellations, and investigations through structured workflow, tracking, and resolution processes.",
            "basic": "• Manual exception handling.\n• Limited tracking of resolution status.\n• Basic communication tools for investigations.",
            "advanced": "• Structured exception management workflows.\n• Digital case tracking and routing.\n• Templated investigation communications.",
            "leading": "• Automated exception categorization and routing.\n• Advanced case management with SLA tracking.\n• Integrated investigation tools across networks.",
            "emerging": "• AI-driven exception resolution and prevention.\n• Predictive exception management.\n• Self-healing payment processes to reduce exceptions.",
        },
        {
            "qid": "10C", "stage": "Reconciliation & Exceptions", 
            "process": "Returns & Cancellations",
            "description": "Processes payment returns, recall requests, and cancellations efficiently while maintaining proper audit trails and customer communication.",
            "basic": "• Manual return processing.\n• Limited cancellation capabilities.\n• Basic customer notifications.",
            "advanced": "• Automated return workflow management.\n• Digital cancellation request handling.\n• Structured customer communications.",
            "leading": "• Real-time return processing and tracking.\n• Integrated cancellation management across networks.\n• Proactive customer notification and resolution.",
            "emerging": "• AI-driven return prevention and management.\n• Blockchain-based payment recall capabilities.\n• Self-service cancellation with intelligent routing.",
        },
        {
            "qid": "10D", "stage": "Reconciliation & Exceptions", 
            "process": "Customer Inquiry Management",
            "description": "Handles customer inquiries about payment status, missing payments, and other issues through efficient investigation and resolution processes.",
            "basic": "• Manual inquiry handling.\n• Limited tracking of inquiries.\n• Basic investigation procedures.",
            "advanced": "• Structured inquiry management system.\n• Digital tracking and audit trail.\n• Template-based investigation procedures.",
            "leading": "• Integrated inquiry management across channels.\n• Real-time payment tracking for customer service.\n• Advanced analytics on inquiry patterns.",
            "emerging": "• AI-powered inquiry resolution with prediction.\n• Self-service tracking with detailed visibility.\n• Proactive issue identification before customer inquiry.",
        },
        
        # Stage 11: Reporting, Analytics & Notifications
        {
            "qid": "11A", "stage": "Reporting, Analytics & Notifications", 
            "process": "Payment Status Notifications",
            "description": "Provides timely updates on payment status to customers through preferred channels, including confirmations, tracking updates, and exception alerts.",
            "basic": "• Limited payment status visibility.\n• Manual status checking by customers.\n• Basic email notifications only.",
            "advanced": "• Automated multi-channel notifications.\n• Self-service payment tracking portal.\n• Configurable alert preferences.",
            "leading": "• Real-time payment status updates.\n• Cross-border payment tracking via SWIFT gpi.\n• Intelligent notification routing based on urgency.",
            "emerging": "• Predictive payment status updates.\n• Conversational interfaces for payment tracking.\n• Ecosystem integration across banks for end-to-end visibility.",
        },
        {
            "qid": "11B", "stage": "Reporting, Analytics & Notifications", 
            "process": "Regulatory Reporting",
            "description": "Generates and submits required regulatory reports related to payments, ensuring accuracy, timeliness, and compliance with reporting obligations.",
            "basic": "• Manual report generation.\n• Basic compliance validation.\n• Limited reporting formats.",
            "advanced": "• Automated report generation.\n• Digital submission capabilities.\n• Validation before submission.",
            "leading": "• Real-time regulatory data collection.\n• Advanced analytics for compliance monitoring.\n• Adaptive reporting for regulatory changes.",
            "emerging": "• AI-driven regulatory interpretation and implementation.\n• Regtech integration for continuous compliance.\n• Predictive compliance monitoring and alerting.",
        },
        {
            "qid": "11C", "stage": "Reporting, Analytics & Notifications", 
            "process": "Customer Reporting & Analytics",
            "description": "Provides customers with reports and analytics on their payment activity, enabling better cash management, reconciliation, and business intelligence.",
            "basic": "• Basic transaction reporting.\n• Limited self-service options.\n• Standard report formats only.",
            "advanced": "• Comprehensive payment reporting portal.\n• Self-service report generation.\n• Multiple export formats.",
            "leading": "• Real-time analytics dashboard.\n• Interactive visualization tools.\n• Customizable reporting views and metrics.",
            "emerging": "• AI-powered payment insights and recommendations.\n• Predictive cash flow analytics.\n• Embedded financial intelligence in customer platforms.",
        },
        {
            "qid": "11D", "stage": "Reporting, Analytics & Notifications", 
            "process": "Business Intelligence",
            "description": "Analyzes payment data to generate business insights, optimize operations, identify trends, and improve service quality.",
            "basic": "• Basic operational reporting.\n• Manual data analysis.\n• Limited metrics tracking.",
            "advanced": "• Structured business intelligence platform.\n• Regular KPI dashboards.\n• Trend analysis capabilities.",
            "leading": "• Advanced analytics with predictive capabilities.\n• Real-time performance monitoring.\n• Machine learning for pattern recognition.",
            "emerging": "• AI-driven business intelligence with recommendations.\n• Autonomous optimization of payment operations.\n• Embedded analytics in operational workflows.",
        },
        
        # Stage 12: Audit, Archival & Compliance
        {
            "qid": "12A", "stage": "Audit, Archival & Compliance", 
            "process": "Payment Archiving",
            "description": "Stores and archives payment data according to retention requirements, ensuring availability for audit, investigation, and compliance purposes.",
            "basic": "• Basic data retention.\n• Manual archiving processes.\n• Limited searchability of archives.",
            "advanced": "• Automated archiving workflows.\n• Digital archive with search capabilities.\n• Policy-based retention management.",
            "leading": "• Intelligent archiving with metadata enrichment.\n• Advanced search and retrieval tools.\n• Integrated compliance validation.",
            "emerging": "• AI-powered archiving with predictive retrieval.\n• Blockchain/DLT for immutable payment records.\n• Content-aware retention optimization.",
        },
        {
            "qid": "12B", "stage": "Audit, Archival & Compliance", 
            "process": "Audit Trail & Logging",
            "description": "Maintains comprehensive logs of all payment activities, user actions, system events, and changes for audit and investigation purposes.",
            "basic": "• Basic system logs.\n• Limited user action tracking.\n• Manual log review processes.",
            "advanced": "• Comprehensive audit logging.\n• Digital audit trail management.\n• Structured log retention and archiving.",
            "leading": "• Real-time audit monitoring and alerting.\n• Advanced log analytics tools.\n• Tamper-evident logging mechanisms.",
            "emerging": "• AI-powered audit log analysis.\n• Blockchain-based immutable audit trails.\n• Predictive compliance monitoring from audit data.",
        },
        {
            "qid": "12C", "stage": "Audit, Archival & Compliance", 
            "process": "Compliance Monitoring",
            "description": "Continuously monitors payment activities for compliance with regulations, internal policies, and industry standards.",
            "basic": "• Periodic manual compliance reviews.\n• Basic policy checks.\n• Limited monitoring scope.",
            "advanced": "• Scheduled automated compliance checks.\n• Comprehensive policy rules engine.\n• Regular compliance reporting.",
            "leading": "• Real-time compliance monitoring and alerts.\n• Advanced analytics for pattern detection.\n• Dynamic rule adaptation to regulatory changes.",
            "emerging": "• AI-driven continuous compliance monitoring.\n• Predictive compliance risk management.\n• Natural language processing of regulatory updates.",
        },
        {
            "qid": "12D", "stage": "Audit, Archival & Compliance", 
            "process": "Data Privacy & Security",
            "description": "Protects payment data through encryption, access controls, data minimization, and other security measures in compliance with privacy regulations.",
            "basic": "• Basic access controls.\n• Limited encryption implementation.\n• Manual privacy impact assessments.",
            "advanced": "• Comprehensive data security framework.\n• Encryption of sensitive data.\n• Regular privacy compliance reviews.",
            "leading": "• Advanced data protection with tokenization.\n• Granular access controls and monitoring.\n• Privacy by design in all processes.",
            "emerging": "• AI-powered anomaly detection for data access.\n• Quantum-resistant encryption.\n• Zero-knowledge proofs for privacy-preserving processing.",
        },
    ]
    
    return data
