import pandas as pd

# This file contains the data for business outcomes and maturity descriptions

# Define option descriptions
OPTION_DESCRIPTIONS = {
    "Basic": {
        "value": 0,
        "description": "Minimal functionality, often manual processes, requiring significant user effort and offering limited capabilities."
    },
    "Advanced": {
        "value": 0.33,
        "description": "Standard industry functionality with some automation and integration, providing reliable but not exceptional service."
    },
    "Leading": {
        "value": 0.66,
        "description": "Above average capabilities with significant automation, integration, and optimization, offering competitive advantage."
    },
    "Emerging": {
        "value": 1.0,
        "description": "Cutting-edge, innovative capabilities leveraging AI, machine learning, and advanced technologies to deliver exceptional service."
    }
}

# Convert process details into dataframe
def load_process_details():
    data = [
        # Stage 1: Payment Initiation & Data Capture
        {
            "qid": "1A", "stage": "Payment Initiation & Data Capture", 
            "process": "Channel Access & Log-In",
            "description": "Provides the customer or corporate user with secure entry points to initiate payments—mobile app, web portal, POS, wallet or ERP/TMS integration, bulk-file upload or APIs/host-to-host.",
            "basic": "• Multiple siloed channels with separate credentials (e.g. branch login, web login, mobile login).\n• No single-sign-on; users must reauthenticate per channel.\n• Slow password/PIN flows, little automation in session management.",
            "advanced": "• Centralized IAM with single-sign-on across channels.\n• Persistent sessions via secure cookies or device trust.\n• Basic adaptive MFA (e.g. step-up for high-value payments).",
            "leading": "• Fully unified CIAM platform: SSO, OAuth2/OIDC, device fingerprinting.\n• Contextual authentication (risk-based MFA triggered automatically).\n• API-first design so third-party apps (ERP, fintech partners) share the same login flow.",
            "emerging": "• Passwordless with behavioral biometrics.\n• AI-driven fraud prevention in login (behavioral biometrics, continuous authentication).\n• Decentralized identity (DID) using verifiable credentials for corporate users.",
        },
        {
            "qid": "1B", "stage": "Payment Initiation & Data Capture", 
            "process": "Payment Setup",
            "description": "The screen or API call where payer enters or uploads the payment details: retail single-payment UI or corporate bulk file (e.g. payroll).",
            "basic": "• Manual UI form for single payment with limited reuse of payees.\n• Corporate uses flat-file templates via SFTP.\n• No intelligent defaults; all fields must be typed.",
            "advanced": "• Pre-populated beneficiary lists, autocomplete of recurring payees.\n• Corporate B2B portal supports CSV/ISO 20022 XML upload with template validation.\n• \"Save as draft\" workflows for approval queues.",
            "leading": "• Guided UI with next-best-action suggestions (AI-driven) for payees/amounts.\n• Bulk template import via API, with dynamic loading of corporate ACH/RTGS parameters.\n• Auto-grouping of bulk payments by payee or category for faster entry.",
            "emerging": "• Conversational-UI or voice-driven payment setup.\n• Zero-touch invoice-to-pay: AI ingests PDF invoices, auto-creates payment batches.\n• Real-time integrations with ERP to auto-trigger payments on invoice receipt.",
        },
        {
            "qid": "1C", "stage": "Payment Initiation & Data Capture", 
            "process": "Data Entry & Input Validation",
            "description": "Ensures the data entered is syntactically & semantically correct—format checks (IBAN, BIC), mandatory fields, and optional real-time lookups (account status, card BIN).",
            "basic": "• Basic form validation with generic error messages.\n• Manual correction loops with full page refresh.\n• No contextual help or inline validation.",
            "advanced": "• Inline validation with field-specific error messages.\n• Format detection & normalization (e.g. auto-format card numbers).\n• Address verification against postal database.",
            "leading": "• Dynamic validation based on payment type & destination country.\n• Beneficiary name & account validation in real-time.\n• PAN/CVV validation against card BIN database.",
            "emerging": "• AI-powered predictive field completion & error correction.\n• Real-time IBAN lookup with beneficiary confirmation API.\n• ML anomaly detection to flag unusual payment characteristics.",
        },
        {
            "qid": "1D", "stage": "Payment Initiation & Data Capture", 
            "process": "Submission & Order Creation",
            "description": "Captures the completed payment order, creates the payment record, and hands off to downstream processing—confirms submission & provides reference number.",
            "basic": "• Batch processing with end-of-day execution.\n• No real-time feedback or status tracking.\n• Manual record creation & tracking.",
            "advanced": "• Real-time order creation with immediate confirmation.\n• Digital receipt with unique reference number.\n• Payment status tracking in customer portal.",
            "leading": "• Event streaming architecture with guaranteed order capture.\n• Multi-channel payment status notifications.\n• Payment history searchable by multiple parameters (date, amount, payee).",
            "emerging": "• Zero-latency distributed ledger recording.\n• Blockchain-based immutable payment record.\n• Full payment lifecycle visibility with real-time status changes.",
        },
        
        # Stage 2: Authentication & Identity Validation
        {
            "qid": "2A", "stage": "Authentication & Identity Validation", 
            "process": "Primary Authentication",
            "description": "Confirms the identity of the payment initiator through username/password challenge, biometrics, passkeys, or other credentials.",
            "basic": "• Simple username/password authentication.\n• No biometric options, only PIN/password.\n• Long session timeout requiring frequent re-auth.",
            "advanced": "• Industry-standard 2FA (SMS OTP, email links).\n• Basic biometric options (fingerprint, face).\n• Security questions for high-risk actions.",
            "leading": "• FIDO2/WebAuthn support with token-based auth.\n• Multiple biometric options on all channels.\n• Intelligent session management based on risk.",
            "emerging": "• Passwordless with passkeys for all channels.\n• Behavioral biometrics as primary auth factor.\n• Continuous authentication throughout payment journey.",
        },
        {
            "qid": "2B", "stage": "Authentication & Identity Validation", 
            "process": "Multi-Factor Authentication",
            "description": "Adds additional verification factors when required by transaction risk, compliance requirements, or to ensure non-repudiation.",
            "basic": "• SMS one-time codes as only second factor.\n• No risk-based MFA triggers.\n• Blanket approach requiring same MFA for all payments.",
            "advanced": "• App-based authenticator options.\n• Basic risk rules trigger step-up auth.\n• Configurable MFA thresholds based on amount.",
            "leading": "• Multiple authenticator options (TOTP, push notifications).\n• Out-of-band verification through multiple channels.\n• Context-aware adaptive authentication.",
            "emerging": "• Presence-based silent authentication.\n• Biometric MFA with liveness detection.\n• AI-driven continuous risk assessment.",
        },
        {
            "qid": "2C", "stage": "Authentication & Identity Validation", 
            "process": "Corporate Authorization",
            "description": "For business accounts, validates the initiator has proper entitlements, mandate & signing authority, and enforces payment limits by role & amount.",
            "basic": "• Static role-based access control.\n• Manual entitlement verification.\n• No integration with corporate hierarchy data.",
            "advanced": "• Automated limit checks during initiation.\n• Pre-defined approval workflows.\n• Role-based dashboards & controls.",
            "leading": "• Dynamic mandate checking against corporate structure.\n• Real-time signature verification against mandate database.\n• Complex approval matrix support (multiple approvers by criteria).",
            "emerging": "• Decentralized identity verification with VC/blockchain.\n• Algorithm-based smart approval routing.\n• Integration with corporate governance systems.",
        },
        {
            "qid": "2D", "stage": "Authentication & Identity Validation", 
            "process": "Session Security",
            "description": "Prevents session hijacking, maintains secure payment context, and protects the authenticated state from theft or replay attacks.",
            "basic": "• Basic cookie-based sessions.\n• Short timeouts with full re-auth required.\n• No detection of session anomalies.",
            "advanced": "• Encrypted session tokens with regular rotation.\n• Session binding to IP address.\n• Automatic logout on inactivity.",
            "leading": "• Advanced device fingerprinting.\n• Certificate pinning for mobile apps.\n• Session continuity across channels.",
            "emerging": "• Zero trust architecture with continuous validation.\n• Real-time risk scoring of session behaviors.\n• Quantum-resistant session cryptography.",
        },
        
        # Stage 3: Pre-Submission Validation
        {
            "qid": "3A", "stage": "Pre-Submission Validation", 
            "process": "Format & Completeness Checks",
            "description": "Validates all required fields are present, properly formatted, and meet the criteria for the specific payment type, channel, and destination.",
            "basic": "• Basic required field validation.\n• Generic error messages.\n• Limited format validation (length, character type).",
            "advanced": "• Payment-type specific validation rules.\n• Clear error identification with correction guidance.\n• Format standardization before submission.",
            "leading": "• Dynamic field requirements based on payment context.\n• Real-time field-level validation for all inputs.\n• Format transformation & normalization.",
            "emerging": "• AI-based predictive validation of complex fields.\n• Metadata enrichment from multiple sources.\n• Semantic validation of payment purpose.",
        },
        {
            "qid": "3B", "stage": "Pre-Submission Validation", 
            "process": "Business Rule Enforcement",
            "description": "Checks payment against business policies like daily limits, duplicate detection, allowed destinations, frequency caps, and balance requirements.",
            "basic": "• Static hard-coded business rules.\n• Basic duplicate payment detection.\n• Manual balance checks.",
            "advanced": "• Centralized rules engine with versioning.\n• Automated funds availability verification.\n• Real-time limit monitoring.",
            "leading": "• Dynamic rules triggered by contextual factors.\n• ML-based duplicate detection (fuzzy matching).\n• Cross-channel rule consistency.",
            "emerging": "• Self-optimizing rules based on payment patterns.\n• Predictive cash flow verification.\n• Natural language policy definition.",
        },
        {
            "qid": "3C", "stage": "Pre-Submission Validation", 
            "process": "Preliminary Compliance Screening",
            "description": "Performs initial screening of payment against sanctions lists, high-risk countries, and suspicious patterns before committing to the payment flow.",
            "basic": "• Basic screening against outdated sanctions lists.\n• No real-time screening during payment initiation.\n• Binary pass/fail with manual review process.",
            "advanced": "• Daily-updated screening lists.\n• Real-time initial screening during payment entry.\n• Name matching with fuzzy logic.",
            "leading": "• API-connected sanctions screening service.\n• Risk-based screening depth based on payment profile.\n• Automated resolution of common false positives.",
            "emerging": "• AI/ML-based screening with continuous learning.\n• Behavioral pattern matching across customer base.\n• Real-time risk scoring with explainable AI decisions.",
        },
        {
            "qid": "3D", "stage": "Pre-Submission Validation", 
            "process": "Real-Time Feedback",
            "description": "Provides immediate validation feedback to payer, suggesting corrections, confirming valid data, or giving processing estimates.",
            "basic": "• Basic form validation with submit-time feedback.\n• Static error messages.\n• No success indicators for valid entry.",
            "advanced": "• Immediate field validation with visual indicators.\n• Real-time data formatting suggestions.\n• Fee calculation transparency.",
            "leading": "• Contextual help with field-specific guidance.\n• Error correction suggestions.\n• Processing time estimates based on payment type and destination.",
            "emerging": "• AI-suggested corrections with learning capability.\n• Real-time beneficiary confirmation.\n• Smart fee optimization suggestions.",
        },
        
        # Stage 4: Payment Orchestration & Routing
        {
            "qid": "4A", "stage": "Payment Orchestration & Routing", 
            "process": "Payment Method Selection",
            "description": "Determines optimal payment rails or methods based on amount, destination, speed needs, cost, and contextual factors.",
            "basic": "• Manual rail selection by user.\n• Limited payment type options.\n• No smart routing capability.",
            "advanced": "• Automated selection based on static rules.\n• Cost vs. speed options presented.\n• Basic cross-border routing.",
            "leading": "• Dynamic routing based on multiple factors.\n• Optimized for speed, cost, or certainty.\n• Alternative route suggestions with trade-offs.",
            "emerging": "• AI-driven optimal rail selection.\n• Real-time payment network status integration.\n• Predictive routing based on success probability.",
        },
        {
            "qid": "4B", "stage": "Payment Orchestration & Routing", 
            "process": "Payment Network Determination",
            "description": "Routes the payment through appropriate networks like ACH, Fedwire, SWIFT, RTP, card networks, FPS, SEPA based on rules and parameters.",
            "basic": "• Limited network connectivity.\n• Manual network selection.\n• No fallback routing.",
            "advanced": "• Rules-based network selection.\n• Automated cut-off time management.\n• Basic fallback options.",
            "leading": "• Dynamic network selection across global options.\n• Real-time network status monitoring.\n• Automated fallback with notification.",
            "emerging": "• AI-optimized multi-path routing.\n• Distributed ledger/blockchain network integration.\n• Predictive outage rerouting.",
        },
        {
            "qid": "4C", "stage": "Payment Orchestration & Routing", 
            "process": "Fee Calculation & Disclosure",
            "description": "Determines and discloses all fees associated with the payment, including FX rates, correspondent fees, and payment network charges.",
            "basic": "• Basic flat fee schedule.\n• No real-time FX quotes.\n• Limited fee transparency.",
            "advanced": "• Dynamic fee calculation for standard rails.\n• Real-time FX rate quotes.\n• Fee breakdown transparency.",
            "leading": "• Complete fee calculation including correspondent costs.\n• Multiple FX rate options with margin disclosure.\n• Fee optimization suggestions.",
            "emerging": "• AI-driven fee optimization across all variables.\n• Predictive FX timing recommendations.\n• DLT-based fee minimization.",
        },
        {
            "qid": "4D", "stage": "Payment Orchestration & Routing", 
            "process": "Exception Handling & Repair",
            "description": "Processes to handle routing failures, network rejections, and unexpected scenarios requiring payment rerouting or repair.",
            "basic": "• Manual exception handling.\n• Basic error notification.\n• Limited repair options.",
            "advanced": "• Automated detection of common errors.\n• Structured repair workflows.\n• Notification of repair needs.",
            "leading": "• Intelligent error classification.\n• Self-healing for common issues.\n• Automated repair for format issues.",
            "emerging": "• AI-powered predictive exception handling.\n• Self-optimizing repair capabilities.\n• Automated rerouting without human intervention.",
        },
        
        # Stage 5: Risk, Fraud & Compliance
        {
            "qid": "5A", "stage": "Risk, Fraud & Compliance", 
            "process": "Transaction Fraud Screening",
            "description": "Advanced fraud detection for transactions, using analytics, machine learning, and pattern recognition to detect anomalies and prevent fraud.",
            "basic": "• Basic rules-based screening.\n• High false positive rates.\n• Reactive fraud controls.",
            "advanced": "• Real-time screening with ML models.\n• Behavioral profiling.\n• Device fingerprinting.",
            "leading": "• Advanced AI models with continuous learning.\n• Network analysis for mule detection.\n• Cross-channel fraud correlation.",
            "emerging": "• Real-time adaptive AI with explainable decisions.\n• Consortium data and federated learning.\n• Behavioral biometrics with continuous authentication.",
        },
        {
            "qid": "5B", "stage": "Risk, Fraud & Compliance", 
            "process": "Sanctions & AML Screening",
            "description": "Validates the payment against sanctions, PEP, and AML watchlists with optimized matching algorithms and risk-based approach.",
            "basic": "• Basic name matching against lists.\n• High false positive rates.\n• Manual resolution of alerts.",
            "advanced": "• Fuzzy matching with multiple parameters.\n• Integrated global watchlists.\n• Semi-automated resolution.",
            "leading": "• Advanced entity resolution algorithms.\n• Risk-based screening depth.\n• Auto-clearing of low-risk hits.",
            "emerging": "• AI-powered contextual screening.\n• Entity relationship mapping.\n• Automated investigation with audit trail.",
        },
        {
            "qid": "5C", "stage": "Risk, Fraud & Compliance", 
            "process": "KYC & Customer Due Diligence",
            "description": "Links payment to customer KYC profiles, applies appropriate due diligence measures, and manages enhanced monitoring for high-risk customers.",
            "basic": "• Static KYC checks at onboarding only.\n• Manual review processes.\n• Limited ongoing monitoring.",
            "advanced": "• Automated periodic KYC refresh.\n• Risk-based customer categorization.\n• Basic ongoing transaction monitoring.",
            "leading": "• Dynamic KYC based on behavior changes.\n• Real-time CDD adaptation.\n• Integrated adverse media monitoring.",
            "emerging": "• Continuous KYC using AI and alternative data.\n• Predictive risk scoring.\n• Self-updating customer risk profiles.",
        },
        {
            "qid": "5D", "stage": "Risk, Fraud & Compliance", 
            "process": "Risk-Based Decision Engine",
            "description": "Centralizes risk decisions across fraud, compliance, and business rules to provide consistent, optimized treatment with minimal friction.",
            "basic": "• Siloed decision systems.\n• Rules-only approach.\n• Manual override processes.",
            "advanced": "• Unified risk scoring.\n• ML-based decision models.\n• Structured exception process.",
            "leading": "• Real-time adaptive risk engine.\n• Customer friction calibration.\n• Dynamic rule optimization.",
            "emerging": "• Self-learning AI decision fabric.\n• Explainable AI for all decisions.\n• Predictive risk intervention.",
        },
        
        # Stage 6: Final Authorisation & Approval
        {
            "qid": "6A", "stage": "Final Authorisation & Approval", 
            "process": "Customer Confirmation",
            "description": "Final verification with the customer for payment approval, using appropriate out-of-band channels based on transaction risk.",
            "basic": "• Basic email/SMS approval links.\n• Same confirmation method for all payments.\n• Limited authentication options.",
            "advanced": "• Mobile app push notifications.\n• Risk-based confirmation method.\n• Multiple authentication options.",
            "leading": "• Omni-channel approval options.\n• Biometric confirmation integration.\n• Contextual approval UX based on risk.",
            "emerging": "• Silent approval for low-risk transactions.\n• Behavioral confirmation signals.\n• Invisible strong authentication.",
        },
        {
            "qid": "6B", "stage": "Final Authorisation & Approval", 
            "process": "Payment Release Decision",
            "description": "Final go/no-go decision point incorporating all checks, balances, and authorizations before releasing the payment for processing.",
            "basic": "• Manual approval workflows.\n• Single-factor authorization.\n• Limited approval delegation.",
            "advanced": "• Automated release for standard payments.\n• Dual-control for high-value transactions.\n• Basic approval hierarchy.",
            "leading": "• Dynamic approval routing based on risk.\n• Multi-level authorization matrix.\n• Real-time payment impact analysis.",
            "emerging": "• AI-driven approval orchestration.\n• Predictive approval routing.\n• Continuous post-approval monitoring.",
        },
        {
            "qid": "6C", "stage": "Final Authorisation & Approval", 
            "process": "Funds Check & Reservation",
            "description": "Validates and reserves sufficient funds, including checking credit facilities and creating memo posts to prevent overdrafts.",
            "basic": "• Point-in-time balance check.\n• No active funds reservation.\n• Manual overdraft handling.",
            "advanced": "• Real-time balance verification.\n• Temporary funds reservation.\n• Automated overdraft decisions.",
            "leading": "• Predictive balance forecasting.\n• Dynamic credit facility access.\n• Intelligent scheduling for funding gaps.",
            "emerging": "• AI cash flow prediction integration.\n• Dynamic liquidity optimization.\n• Cross-account smart funding.",
        },
        {
            "qid": "6D", "stage": "Final Authorisation & Approval", 
            "process": "Regulatory Compliance Confirmation",
            "description": "Final regulatory checks including purpose verification, reporting thresholds, cross-border requirements, and documentation completeness.",
            "basic": "• Basic regulatory field validation.\n• Manual regulatory reporting.\n• Limited cross-border compliance capabilities.",
            "advanced": "• Automated reporting threshold detection.\n• Digital regulatory filing preparation.\n• Country-specific validation rules.",
            "leading": "• Real-time compliance determination.\n• Integrated regulatory reporting.\n• Cross-border documentation automation.",
            "emerging": "• AI-powered regulatory interpretation.\n• Predictive compliance monitoring.\n• Automated adaptation to regulatory changes.",
        },
        
        # Stage 7: Message Generation & Transformation
        {
            "qid": "7A", "stage": "Message Generation & Transformation", 
            "process": "Format Transformation",
            "description": "Converts payment data into the required format for the target network (ISO 20022, SWIFT MT, FedWire, etc.) with proper field mapping.",
            "basic": "• Manual format mapping.\n• Limited format support.\n• Error-prone transformation.",
            "advanced": "• Rules-based format conversion.\n• Support for major standards.\n• Mapping template library.",
            "leading": "• Dynamic schema-driven transformation.\n• Comprehensive format coverage.\n• Automated data enrichment.",
            "emerging": "• AI-powered semantic mapping.\n• Self-updating format transformations.\n• Cross-standard data harmonization.",
        },
        {
            "qid": "7B", "stage": "Message Generation & Transformation", 
            "process": "Validation & Enrichment",
            "description": "Validates the transformed message against network rules, enriches with required data, and ensures compliance with format specifications.",
            "basic": "• Basic syntax validation.\n• Manual data enrichment.\n• Limited error correction.",
            "advanced": "• Network-specific rule validation.\n• Automated data lookup & enrichment.\n• Error suggestion capabilities.",
            "leading": "• Comprehensive semantic validation.\n• Dynamic field enrichment.\n• Pre-validation against network simulators.",
            "emerging": "• AI-based message optimization.\n• Predictive validation enhancement.\n• Self-correcting message generation.",
        },
        {
            "qid": "7C", "stage": "Message Generation & Transformation", 
            "process": "Payment Metadata Management",
            "description": "Manages additional data, references, and metadata needed for reconciliation, tracking, and business processes throughout the payment lifecycle.",
            "basic": "• Basic payment references.\n• Limited metadata support.\n• Manual tracking information.",
            "advanced": "• Structured metadata framework.\n• End-to-end tracking support.\n• Standard reference data model.",
            "leading": "• Rich metadata with business context.\n• Cross-system identifier management.\n• Advanced payment state modeling.",
            "emerging": "• Semantic metadata with AI interpretation.\n• Distributed metadata synchronization.\n• Self-describing payment objects.",
        },
        {
            "qid": "7D", "stage": "Message Generation & Transformation", 
            "process": "Repair & Exception Handling",
            "description": "Handles message generation failures, format errors, and data issues with automated repair workflows and user intervention when needed.",
            "basic": "• Manual error resolution.\n• Limited error detection.\n• Basic error reporting.",
            "advanced": "• Structured repair workflows.\n• Detailed error classification.\n• Guided resolution steps.",
            "leading": "• Automated repair for common issues.\n• Pattern-based error prediction.\n• Self-service repair portals.",
            "emerging": "• AI-powered automated repair.\n• Predictive error prevention.\n• Continuous learning repair systems.",
        },
        
        # Stage 8: Transmission, Clearing & ACK
        {
            "qid": "8A", "stage": "Transmission, Clearing & ACK", 
            "process": "Network Connectivity & Security",
            "description": "Secure connections to payment networks, using appropriate protocols, encryption, authentication, and high-availability designs.",
            "basic": "• Basic single-channel connectivity.\n• Limited encryption standards.\n• Manual failover processes.",
            "advanced": "• Multi-channel connectivity.\n• Industry standard encryption.\n• Automated failover capabilities.",
            "leading": "• High-availability network design.\n• Advanced encryption & key management.\n• Real-time network monitoring.",
            "emerging": "• Zero-trust network architecture.\n• Quantum-resistant encryption.\n• Self-healing connectivity.",
        },
        {
            "qid": "8B", "stage": "Transmission, Clearing & ACK", 
            "process": "Message Transmission & Tracking",
            "description": "Transmits messages to appropriate networks and tracks delivery status, acknowledgments, and network responses.",
            "basic": "• Basic transmission logging.\n• Manual status checking.\n• Limited delivery confirmation.",
            "advanced": "• Real-time transmission monitoring.\n• Automated status tracking.\n• ACK/NACK handling automation.",
            "leading": "• End-to-end payment tracking.\n• Proactive transmission issue alerts.\n• Advanced retry logic with escalation.",
            "emerging": "• Predictive transmission optimization.\n• AI-driven routing decisions.\n• Self-monitoring message delivery.",
        },
        {
            "qid": "8C", "stage": "Transmission, Clearing & ACK", 
            "process": "Clearing Integration & Monitoring",
            "description": "Interfaces with clearing systems, monitors clearing cycles, and handles settlement windows across networks and countries.",
            "basic": "• Basic clearing cycle awareness.\n• Manual settlement window tracking.\n• Limited clearing status visibility.",
            "advanced": "• Real-time clearing status monitoring.\n• Automated settlement window alerts.\n• Multi-network clearing dashboards.",
            "leading": "• Proactive clearing cycle management.\n• Dynamic settlement optimization.\n• Cross-border clearing orchestration.",
            "emerging": "• AI-driven clearing optimization.\n• Predictive settlement forecasting.\n• Real-time cross-network liquidity management.",
        },
        {
            "qid": "8D", "stage": "Transmission, Clearing & ACK", 
            "process": "Exception & Rejection Handling",
            "description": "Processes network rejections, validation failures, and other exceptions with appropriate routing to repair or notification channels.",
            "basic": "• Manual rejection processing.\n• Basic error notification.\n• Limited rejection tracking.",
            "advanced": "• Structured rejection workflows.\n• Automated notification routing.\n• Rejection reason classification.",
            "leading": "• Intelligent rejection handling.\n• Self-service rejection resolution.\n• Pattern analysis for systemic issues.",
            "emerging": "• AI-powered rejection resolution.\n• Predictive rejection prevention.\n• Network-aware smart retries.",
        },
        
        # Stage 9: Settlement & Funds Movement
        {
            "qid": "9A", "stage": "Settlement & Funds Movement", 
            "process": "Settlement Processing",
            "description": "Manages the final funds settlement process across correspondent accounts, nostro/vostro relationships, or central bank facilities.",
            "basic": "• Basic settlement recording.\n• Manual nostro reconciliation.\n• Limited settlement optimization.",
            "advanced": "• Automated settlement processing.\n• Real-time nostro monitoring.\n• Basic liquidity forecasting.",
            "leading": "• Dynamic settlement routing.\n• Predictive nostro management.\n• Cross-currency netting optimization.",
            "emerging": "• AI-driven settlement optimization.\n• Real-time settlement across DLT networks.\n• Automated liquidity management.",
        },
        {
            "qid": "9B", "stage": "Settlement & Funds Movement", 
            "process": "Liquidity Management",
            "description": "Optimizes intraday liquidity usage, manages funding sources, and ensures sufficient liquidity across settlement accounts.",
            "basic": "• Basic account balance monitoring.\n• Manual funding transfers.\n• Limited liquidity planning.",
            "advanced": "• Real-time liquidity dashboards.\n• Scheduled funding transfers.\n• Intraday overdraft monitoring.",
            "leading": "• Dynamic liquidity forecasting.\n• Automated funding optimization.\n• Cross-network liquidity pooling.",
            "emerging": "• AI-powered liquidity prediction.\n• Just-in-time funding automation.\n• Self-optimizing liquidity distribution.",
        },
        {
            "qid": "9C", "stage": "Settlement & Funds Movement", 
            "process": "Position Management",
            "description": "Monitors and manages currency positions, exposure, and ensures funding for cross-border and cross-currency payments.",
            "basic": "• End-of-day position monitoring.\n• Manual FX conversion processes.\n• Basic currency exposure tracking.",
            "advanced": "• Intraday position monitoring.\n• Scheduled FX position adjustments.\n• Automated threshold alerts.",
            "leading": "• Real-time currency position management.\n• Dynamic FX execution strategy.\n• Cross-entity position netting.",
            "emerging": "• AI-driven position optimization.\n• Predictive currency exposure management.\n• Automated cross-currency liquidity.",
        },
        {
            "qid": "9D", "stage": "Settlement & Funds Movement", 
            "process": "Settlement Confirmation & Notification",
            "description": "Processes settlement confirmations from networks, nostro accounts, and provides appropriate notifications to internal and external parties.",
            "basic": "• Basic settlement status tracking.\n• Limited confirmation processing.\n• Manual client notifications.",
            "advanced": "• Automated confirmation processing.\n• Structured notification routing.\n• Client-configurable alerts.",
            "leading": "• Real-time settlement visibility.\n• Omni-channel notification delivery.\n• Advanced settlement status APIs.",
            "emerging": "• Instant settlement confirmation.\n• Context-aware smart notifications.\n• Distributed ledger settlement proof.",
        },
        
        # Stage 10: Reconciliation & Exceptions
        {
            "qid": "10A", "stage": "Reconciliation & Exceptions", 
            "process": "Transaction Reconciliation",
            "description": "Reconciles transactions across internal systems, networks, and nostro accounts to ensure data consistency and identify discrepancies.",
            "basic": "• Batch reconciliation processes.\n• Manual exception handling.\n• Limited matching capabilities.",
            "advanced": "• Near-real-time reconciliation.\n• Rule-based exception routing.\n• Multi-level matching logic.",
            "leading": "• Real-time continuous reconciliation.\n• Pattern recognition for unmatched items.\n• Self-service exception portals.",
            "emerging": "• AI-powered reconciliation engines.\n• Predictive exception prevention.\n• Autonomous reconciliation workflow.",
        },
        {
            "qid": "10B", "stage": "Reconciliation & Exceptions", 
            "process": "Exception Management",
            "description": "Identifies, classifies, routes, and tracks exceptions through to resolution, with appropriate workflows and SLA management.",
            "basic": "• Manual exception identification.\n• Spreadsheet-based tracking.\n• Limited resolution workflows.",
            "advanced": "• Automated exception detection.\n• Structured workflow management.\n• SLA monitoring and alerts.",
            "leading": "• Pattern-based exception classification.\n• Intelligent work distribution.\n• Root cause analysis integration.",
            "emerging": "• AI-driven exception resolution.\n• Predictive exception identification.\n• Self-optimizing workflow routing.",
        },
        {
            "qid": "10C", "stage": "Reconciliation & Exceptions", 
            "process": "Repair & Reprocessing",
            "description": "Corrects and reprocesses failed or returned payments with appropriate tracking, audit trail, and customer communication.",
            "basic": "• Manual repair processes.\n• Limited reprocessing capabilities.\n• Basic audit logging.",
            "advanced": "• Guided repair workflows.\n• Automated resubmission options.\n• Structured audit trail.",
            "leading": "• Intelligent repair suggestions.\n• Version-controlled payment modification.\n• Customer-integrated repair communication.",
            "emerging": "• AI-powered repair automation.\n• Predictive repair optimization.\n• Self-healing payment processes.",
        },
        {
            "qid": "10D", "stage": "Reconciliation & Exceptions", 
            "process": "Returns & Cancellation Processing",
            "description": "Handles payment returns, recalls, and cancellation requests with appropriate customer notification and posting reversal.",
            "basic": "• Manual return processing.\n• Basic cancellation capabilities.\n• Limited return reason tracking.",
            "advanced": "• Structured return workflows.\n• Automated return notifications.\n• Cancellation request tracking.",
            "leading": "• Network-integrated cancellation services.\n• Real-time return processing.\n• Advanced return analytics.",
            "emerging": "• AI-powered return prediction.\n• Smart cancellation optimization.\n• Distributed ledger payment recalls.",
        },
        
        # Stage 11: Reporting, Analytics & Notifications
        {
            "qid": "11A", "stage": "Reporting, Analytics & Notifications", 
            "process": "Client Reporting & Notifications",
            "description": "Provides clients with transaction status updates, confirmations, and reporting through appropriate channels and formats.",
            "basic": "• Basic email notifications.\n• Static PDF statements.\n• Limited self-service reporting.",
            "advanced": "• Multi-channel notification options.\n• Web-based interactive reporting.\n• API access to transaction data.",
            "leading": "• Omni-channel notification orchestration.\n• Real-time dashboards and analytics.\n• White-labeled client portal solutions.",
            "emerging": "• Context-aware smart notifications.\n• Predictive analytics for clients.\n• Conversational reporting interfaces.",
        },
        {
            "qid": "11B", "stage": "Reporting, Analytics & Notifications", 
            "process": "Operational Reporting & Dashboards",
            "description": "Provides internal operational teams with monitoring, analytics, and reporting capabilities for payment operations.",
            "basic": "• Static operational reports.\n• Manual data extraction process.\n• Limited KPI tracking.",
            "advanced": "• Near-real-time operational dashboards.\n• Standard KPI visualization.\n• Self-service report generation.",
            "leading": "• Real-time operational intelligence.\n• Predictive volume and exception forecasting.\n• Advanced process analytics.",
            "emerging": "• AI-powered operation optimization.\n• Anomaly detection with root cause analysis.\n• Autonomous process improvement.",
        },
        {
            "qid": "11C", "stage": "Reporting, Analytics & Notifications", 
            "process": "Payment Analytics & Insights",
            "description": "Analyzes payment data for insights on trends, patterns, opportunities, and risks across customers and payment types.",
            "basic": "• Basic transaction volume reports.\n• Manual trend analysis.\n• Limited data visualization.",
            "advanced": "• Customer segmentation analytics.\n• Payment flow visualization.\n• Regular trend reporting.",
            "leading": "• Advanced payment pattern recognition.\n• Predictive volume and behavior models.\n• Interactive analytics self-service.",
            "emerging": "• AI-driven payment behavior analysis.\n• Real-time opportunity identification.\n• Prescriptive action recommendation.",
        },
        {
            "qid": "11D", "stage": "Reporting, Analytics & Notifications", 
            "process": "Performance Analytics",
            "description": "Measures and analyzes payment process KPIs, SLAs, and performance metrics to identify optimization opportunities.",
            "basic": "• Manual KPI calculation.\n• Limited performance tracking.\n• Basic SLA reporting.",
            "advanced": "• Automated KPI dashboards.\n• Historical trend analysis.\n• SLA breach notification system.",
            "leading": "• Real-time performance monitoring.\n• Predictive SLA risk alerts.\n• Root cause analysis integration.",
            "emerging": "• AI-powered performance optimization.\n• Autonomous bottleneck identification.\n• Self-tuning process parameters.",
        },
        
        # Stage 12: Audit, Archival & Compliance
        {
            "qid": "12A", "stage": "Audit, Archival & Compliance", 
            "process": "Regulatory Reporting",
            "description": "Generates and submits required regulatory reports for payments such as FBAR, BSA, sanctions monitoring, and cross-border reporting.",
            "basic": "• Manual regulatory report preparation.\n• Basic compliance checks.\n• Limited regulatory coverage.",
            "advanced": "• Automated regulatory report generation.\n• Scheduled reporting workflows.\n• Multi-jurisdiction compliance.",
            "leading": "• Real-time compliance monitoring.\n• Integrated regulatory filing.\n• Cross-regulation data harmonization.",
            "emerging": "• AI-driven regulatory interpretation.\n• Predictive compliance monitoring.\n• Automated regulatory adaptation.",
        },
        {
            "qid": "12B", "stage": "Audit, Archival & Compliance", 
            "process": "Payment Archival & Retrieval",
            "description": "Archives payment records for regulatory retention periods and provides search and retrieval capabilities for audits and investigations.",
            "basic": "• Basic transaction data storage.\n• Manual retrieval processes.\n• Limited search capabilities.",
            "advanced": "• Structured data archival strategy.\n• Self-service search interfaces.\n• Retention policy enforcement.",
            "leading": "• Comprehensive payment lifecycle archival.\n• Advanced search with filters and aggregation.\n• Legal hold and investigation tools.",
            "emerging": "• AI-powered semantic search.\n• Blockchain-verified immutable records.\n• Content-aware data classification.",
        },
        {
            "qid": "12C", "stage": "Audit, Archival & Compliance", 
            "process": "Audit Trail & Non-Repudiation",
            "description": "Maintains comprehensive audit trails of all actions, approvals, and changes with user attribution and timestamp for non-repudiation.",
            "basic": "• Basic action logging.\n• Limited user tracking.\n• Manual audit extraction.",
            "advanced": "• Detailed activity audit trails.\n• User and system action tracking.\n• Structured audit data model.",
            "leading": "• Comprehensive lifecycle audit coverage.\n• Tamper-evident audit storage.\n• Advanced audit analytics.",
            "emerging": "• Blockchain-based immutable audit trails.\n• AI-powered audit pattern analysis.\n• Cryptographic non-repudiation proof.",
        },
        {
            "qid": "12D", "stage": "Audit, Archival & Compliance", 
            "process": "Compliance Monitoring & Testing",
            "description": "Ongoing monitoring of compliance requirements, periodic testing, and continuous improvement of controls and processes.",
            "basic": "• Manual compliance checking.\n• Annual control reviews.\n• Limited monitoring coverage.",
            "advanced": "• Scheduled compliance testing.\n• Automated control monitoring.\n• Regular compliance reporting.",
            "leading": "• Continuous compliance monitoring.\n• Integrated control testing.\n• Compliance analytics dashboard.",
            "emerging": "• AI-driven compliance surveillance.\n• Predictive control failure detection.\n• Autonomous compliance optimization.",
        }
    ]
    return data
